/* HelpDesk asincrónico y newsletter. Reutiliza las consultas de soporte existentes. */
GO
IF COL_LENGTH(N'dbo.ConsultaSoporte', N'Categoria') IS NULL ALTER TABLE dbo.ConsultaSoporte ADD Categoria NVARCHAR(100) NOT NULL CONSTRAINT DF_ConsultaSoporte_Categoria DEFAULT N'Otro';
IF COL_LENGTH(N'dbo.ConsultaSoporte', N'IdSuscripcion') IS NULL ALTER TABLE dbo.ConsultaSoporte ADD IdSuscripcion INT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = N'FK_ConsultaSoporte_Suscripcion') ALTER TABLE dbo.ConsultaSoporte ADD CONSTRAINT FK_ConsultaSoporte_Suscripcion FOREIGN KEY(IdSuscripcion) REFERENCES dbo.Suscripcion(ID);
GO
IF OBJECT_ID(N'dbo.CategoriaNoticia', N'U') IS NULL CREATE TABLE dbo.CategoriaNoticia (ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CategoriaNoticia PRIMARY KEY, Nombre NVARCHAR(100) NOT NULL CONSTRAINT UQ_CategoriaNoticia_Nombre UNIQUE, Descripcion NVARCHAR(300) NOT NULL, Activo BIT NOT NULL CONSTRAINT DF_CategoriaNoticia_Activo DEFAULT 1);
IF OBJECT_ID(N'dbo.Noticia', N'U') IS NULL CREATE TABLE dbo.Noticia (ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Noticia PRIMARY KEY, IdCategoriaNoticia INT NOT NULL, Titulo NVARCHAR(200) NOT NULL, Contenido NVARCHAR(MAX) NOT NULL, ImagenUrl NVARCHAR(1000) NULL, FechaPublicacion DATETIME2 NOT NULL, FechaVencimiento DATETIME2 NULL, Activo BIT NOT NULL CONSTRAINT DF_Noticia_Activo DEFAULT 1, DifusionEnviada BIT NOT NULL CONSTRAINT DF_Noticia_Difusion DEFAULT 0, FechaEnvioNewsletter DATETIME2 NULL, CONSTRAINT FK_Noticia_Categoria FOREIGN KEY(IdCategoriaNoticia) REFERENCES dbo.CategoriaNoticia(ID));
IF OBJECT_ID(N'dbo.SuscripcionNewsletter', N'U') IS NULL CREATE TABLE dbo.SuscripcionNewsletter (ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SuscripcionNewsletter PRIMARY KEY, IdUsuario INT NOT NULL, IdCategoriaNoticia INT NOT NULL, Activo BIT NOT NULL CONSTRAINT DF_SuscripcionNewsletter_Activo DEFAULT 1, FechaAlta DATETIME2 NOT NULL CONSTRAINT DF_SuscripcionNewsletter_FechaAlta DEFAULT SYSDATETIME(), CONSTRAINT UQ_SuscripcionNewsletter UNIQUE(IdUsuario, IdCategoriaNoticia), CONSTRAINT FK_SuscripcionNewsletter_Usuario FOREIGN KEY(IdUsuario) REFERENCES dbo.Usuario(ID), CONSTRAINT FK_SuscripcionNewsletter_Categoria FOREIGN KEY(IdCategoriaNoticia) REFERENCES dbo.CategoriaNoticia(ID));
GO
MERGE dbo.CategoriaNoticia AS destino USING (VALUES (N'Producto', N'Mejoras y funciones de TeamBalance.'), (N'Seguridad', N'Avisos de seguridad y cuentas.'), (N'Novedades', N'Comunicaciones generales de TeamBalance.'), (N'Mantenimiento', N'Cambios operativos y mantenimientos programados.')) AS origen(Nombre, Descripcion) ON destino.Nombre = origen.Nombre WHEN MATCHED THEN UPDATE SET Descripcion = origen.Descripcion, Activo = 1 WHEN NOT MATCHED THEN INSERT(Nombre, Descripcion) VALUES(origen.Nombre, origen.Descripcion);
GO
UPDATE dbo.ConsultaSoporte SET Estado = CASE Estado WHEN N'Abierto' THEN N'Pendiente' WHEN N'En análisis' THEN N'En revisión' WHEN N'Respondido' THEN N'Respondida' WHEN N'Cerrado' THEN N'Resuelta' ELSE Estado END WHERE Estado IN (N'Abierto', N'En análisis', N'Respondido', N'Cerrado');
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_CrearConsulta @IdUsuario INT, @IdAgencia INT = NULL, @IdSuscripcion INT = NULL, @Categoria NVARCHAR(100), @Asunto NVARCHAR(400), @Descripcion NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; INSERT INTO dbo.ConsultaSoporte(IdUsuario,IdAgencia,IdSuscripcion,Categoria,Asunto,Descripcion,Estado,FechaCreacion,FechaActualizacion,Activo) VALUES(@IdUsuario,@IdAgencia,@IdSuscripcion,@Categoria,@Asunto,@Descripcion,N'Pendiente',SYSDATETIME(),SYSDATETIME(),1); DECLARE @Id INT=CONVERT(INT,SCOPE_IDENTITY()); EXEC dbo.usp_HelpDesk_ConsultarDetalle @Id; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_ConsultarPropias @IdUsuario INT AS BEGIN SET NOCOUNT ON; SELECT C.ID,C.IdUsuario,C.IdAgencia,C.IdSuscripcion,C.Categoria,C.Asunto,C.Descripcion,C.Estado,C.FechaCreacion,C.FechaActualizacion, CONCAT(U.Nombre,N' ',U.Apellido) NombreSolicitante,U.Email EmailSolicitante,A.NombreComercial NombreAgencia,P.Nombre NombrePlan,(SELECT COUNT(1) FROM dbo.MensajeConsultaSoporte M WHERE M.IdConsultaSoporte=C.ID AND M.Activo=1) CantidadMensajes FROM dbo.ConsultaSoporte C INNER JOIN dbo.Usuario U ON U.ID=C.IdUsuario LEFT JOIN dbo.Agencia A ON A.ID=C.IdAgencia LEFT JOIN dbo.Suscripcion S ON S.ID=C.IdSuscripcion LEFT JOIN dbo.PlanComercial P ON P.ID=S.IdPlanComercial WHERE C.IdUsuario=@IdUsuario AND C.Activo=1 ORDER BY C.FechaActualizacion DESC; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_ConsultarBandeja @Estado NVARCHAR(100) = NULL AS BEGIN SET NOCOUNT ON; SELECT C.ID,C.IdUsuario,C.IdAgencia,C.IdSuscripcion,C.Categoria,C.Asunto,C.Descripcion,C.Estado,C.FechaCreacion,C.FechaActualizacion, CONCAT(U.Nombre,N' ',U.Apellido) NombreSolicitante,U.Email EmailSolicitante,A.NombreComercial NombreAgencia,P.Nombre NombrePlan,(SELECT COUNT(1) FROM dbo.MensajeConsultaSoporte M WHERE M.IdConsultaSoporte=C.ID AND M.Activo=1) CantidadMensajes FROM dbo.ConsultaSoporte C INNER JOIN dbo.Usuario U ON U.ID=C.IdUsuario LEFT JOIN dbo.Agencia A ON A.ID=C.IdAgencia LEFT JOIN dbo.Suscripcion S ON S.ID=C.IdSuscripcion LEFT JOIN dbo.PlanComercial P ON P.ID=S.IdPlanComercial WHERE C.Activo=1 AND (@Estado IS NULL OR C.Estado=@Estado) ORDER BY CASE C.Estado WHEN N'Pendiente' THEN 1 WHEN N'En revisión' THEN 2 WHEN N'Respondida' THEN 3 ELSE 4 END,C.FechaActualizacion DESC; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_ConsultarDetalle @IdConsulta INT AS BEGIN SET NOCOUNT ON; SELECT C.ID,C.IdUsuario,C.IdAgencia,C.IdSuscripcion,C.Categoria,C.Asunto,C.Descripcion,C.Estado,C.FechaCreacion,C.FechaActualizacion, CONCAT(U.Nombre,N' ',U.Apellido) NombreSolicitante,U.Email EmailSolicitante,A.NombreComercial NombreAgencia,P.Nombre NombrePlan,(SELECT COUNT(1) FROM dbo.MensajeConsultaSoporte M WHERE M.IdConsultaSoporte=C.ID AND M.Activo=1) CantidadMensajes FROM dbo.ConsultaSoporte C INNER JOIN dbo.Usuario U ON U.ID=C.IdUsuario LEFT JOIN dbo.Agencia A ON A.ID=C.IdAgencia LEFT JOIN dbo.Suscripcion S ON S.ID=C.IdSuscripcion LEFT JOIN dbo.PlanComercial P ON P.ID=S.IdPlanComercial WHERE C.ID=@IdConsulta AND C.Activo=1; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_ConsultarMensajes @IdConsulta INT AS BEGIN SET NOCOUNT ON; SELECT M.ID,M.IdUsuario,CONCAT(U.Nombre,N' ',U.Apellido) NombreUsuario,CONVERT(BIT,CASE WHEN R.TipoUsuario=N'Soporte' THEN 1 ELSE 0 END) EsSoporte,M.Mensaje,M.Fecha FROM dbo.MensajeConsultaSoporte M INNER JOIN dbo.Usuario U ON U.ID=M.IdUsuario INNER JOIN dbo.Rol R ON R.ID=U.IdRol WHERE M.IdConsultaSoporte=@IdConsulta AND M.Activo=1 ORDER BY M.Fecha,M.ID; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_AgregarMensaje @IdConsulta INT,@IdUsuario INT,@Mensaje NVARCHAR(MAX),@Estado NVARCHAR(100) AS BEGIN SET NOCOUNT ON; IF NOT EXISTS(SELECT 1 FROM dbo.ConsultaSoporte WHERE ID=@IdConsulta AND Activo=1) THROW 54001,'La consulta indicada no existe.',1; INSERT INTO dbo.MensajeConsultaSoporte(IdConsultaSoporte,IdUsuario,Mensaje,Fecha,Activo) VALUES(@IdConsulta,@IdUsuario,@Mensaje,SYSDATETIME(),1); UPDATE dbo.ConsultaSoporte SET Estado=@Estado,FechaActualizacion=SYSDATETIME() WHERE ID=@IdConsulta; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_HelpDesk_CambiarEstado @IdConsulta INT,@Estado NVARCHAR(100) AS BEGIN SET NOCOUNT ON; UPDATE dbo.ConsultaSoporte SET Estado=@Estado,FechaActualizacion=SYSDATETIME() WHERE ID=@IdConsulta AND Activo=1; IF @@ROWCOUNT=0 THROW 54002,'La consulta indicada no existe.',1; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_ConsultarCategorias AS BEGIN SET NOCOUNT ON; SELECT ID,Nombre,Descripcion,Activo FROM dbo.CategoriaNoticia WHERE Activo=1 ORDER BY Nombre; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_ConsultarPublicas AS BEGIN SET NOCOUNT ON; SELECT N.ID,N.IdCategoriaNoticia,C.Nombre Categoria,N.Titulo,N.Contenido,N.ImagenUrl,N.FechaPublicacion,N.FechaVencimiento,N.Activo,N.DifusionEnviada FROM dbo.Noticia N INNER JOIN dbo.CategoriaNoticia C ON C.ID=N.IdCategoriaNoticia WHERE N.Activo=1 AND N.FechaPublicacion<=SYSDATETIME() AND (N.FechaVencimiento IS NULL OR N.FechaVencimiento>SYSDATETIME()) ORDER BY N.FechaPublicacion DESC,N.ID DESC; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_ConsultarGestion AS BEGIN SET NOCOUNT ON; SELECT N.ID,N.IdCategoriaNoticia,C.Nombre Categoria,N.Titulo,N.Contenido,N.ImagenUrl,N.FechaPublicacion,N.FechaVencimiento,N.Activo,N.DifusionEnviada FROM dbo.Noticia N INNER JOIN dbo.CategoriaNoticia C ON C.ID=N.IdCategoriaNoticia ORDER BY N.Activo DESC,N.FechaPublicacion DESC,N.ID DESC; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_Guardar @IdCategoria INT,@Titulo NVARCHAR(200),@Contenido NVARCHAR(MAX),@ImagenUrl NVARCHAR(1000)=NULL,@FechaPublicacion DATETIME2,@FechaVencimiento DATETIME2=NULL AS BEGIN SET NOCOUNT ON; IF NOT EXISTS(SELECT 1 FROM dbo.CategoriaNoticia WHERE ID=@IdCategoria AND Activo=1) THROW 54003,'La categoría indicada no está disponible.',1; INSERT INTO dbo.Noticia(IdCategoriaNoticia,Titulo,Contenido,ImagenUrl,FechaPublicacion,FechaVencimiento,Activo,DifusionEnviada) VALUES(@IdCategoria,@Titulo,@Contenido,@ImagenUrl,@FechaPublicacion,@FechaVencimiento,1,0); DECLARE @Id INT=CONVERT(INT,SCOPE_IDENTITY()); SELECT N.ID,N.IdCategoriaNoticia,C.Nombre Categoria,N.Titulo,N.Contenido,N.ImagenUrl,N.FechaPublicacion,N.FechaVencimiento,N.Activo,N.DifusionEnviada FROM dbo.Noticia N INNER JOIN dbo.CategoriaNoticia C ON C.ID=N.IdCategoriaNoticia WHERE N.ID=@Id; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_Bajar @IdNoticia INT AS BEGIN SET NOCOUNT ON; UPDATE dbo.Noticia SET Activo=0 WHERE ID=@IdNoticia AND Activo=1; IF @@ROWCOUNT=0 THROW 54004,'La novedad indicada no existe o ya fue dada de baja.',1; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_ConsultarPreferencias @IdUsuario INT AS BEGIN SET NOCOUNT ON; SELECT IdCategoriaNoticia FROM dbo.SuscripcionNewsletter WHERE IdUsuario=@IdUsuario AND Activo=1; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_GuardarPreferencias @IdUsuario INT,@CategoriasJson NVARCHAR(MAX) AS BEGIN SET NOCOUNT ON; UPDATE dbo.SuscripcionNewsletter SET Activo=0 WHERE IdUsuario=@IdUsuario; INSERT INTO dbo.SuscripcionNewsletter(IdUsuario,IdCategoriaNoticia,Activo) SELECT @IdUsuario,CONVERT(INT,[value]),1 FROM OPENJSON(@CategoriasJson) WHERE EXISTS(SELECT 1 FROM dbo.CategoriaNoticia C WHERE C.ID=CONVERT(INT,[value]) AND C.Activo=1) AND NOT EXISTS(SELECT 1 FROM dbo.SuscripcionNewsletter S WHERE S.IdUsuario=@IdUsuario AND S.IdCategoriaNoticia=CONVERT(INT,[value])); UPDATE S SET Activo=1,FechaAlta=SYSDATETIME() FROM dbo.SuscripcionNewsletter S INNER JOIN OPENJSON(@CategoriasJson) J ON S.IdCategoriaNoticia=CONVERT(INT,J.[value]) WHERE S.IdUsuario=@IdUsuario; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_ConsultarPendientesDifusion AS BEGIN SET NOCOUNT ON; SELECT N.ID,N.IdCategoriaNoticia,C.Nombre Categoria,N.Titulo,N.Contenido,N.ImagenUrl,N.FechaPublicacion,N.FechaVencimiento,N.Activo,N.DifusionEnviada FROM dbo.Noticia N INNER JOIN dbo.CategoriaNoticia C ON C.ID=N.IdCategoriaNoticia WHERE N.Activo=1 AND N.DifusionEnviada=0 AND N.FechaPublicacion<=SYSDATETIME() AND (N.FechaVencimiento IS NULL OR N.FechaVencimiento>SYSDATETIME()); END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_ConsultarDestinatarios @IdNoticia INT AS BEGIN SET NOCOUNT ON; SELECT U.Email,U.Nombre FROM dbo.Noticia N INNER JOIN dbo.SuscripcionNewsletter S ON S.IdCategoriaNoticia=N.IdCategoriaNoticia AND S.Activo=1 INNER JOIN dbo.Usuario U ON U.ID=S.IdUsuario AND U.Activo=1 WHERE N.ID=@IdNoticia; END;
GO
CREATE OR ALTER PROCEDURE dbo.usp_Novedades_MarcarDifundida @IdNoticia INT AS BEGIN SET NOCOUNT ON; UPDATE dbo.Noticia SET DifusionEnviada=1,FechaEnvioNewsletter=SYSDATETIME() WHERE ID=@IdNoticia; END;
GO
