import { Injectable, signal } from '@angular/core';

export type LanguageCode = 'es' | 'en';
export type CultureCode = 'es-AR' | 'en-US';

type TranslationDictionary = Record<string, string>;

@Injectable({
  providedIn: 'root',
})
export class LocalizationService {

  private readonly translations: Record<LanguageCode, TranslationDictionary> = {

    es: {
      'common.save': 'Guardar',
      'common.cancel': 'Cancelar',
      'common.search': 'Buscar',
      'common.close': 'Cerrar',
      'common.edit': 'Editar',
      'common.create': 'Crear',
      'common.update': 'Actualizar',
      'common.active': 'Activo',
      'common.inactive': 'Inactivo',
      'common.activate': 'Activar',
      'common.deactivate': 'Dar de baja',
      'common.loading': 'Cargando…',
      'common.retry': 'Reintentar',
      'common.included': 'Incluido',
      'common.required': 'Completá este campo.',

      'signin': 'Iniciar sesión',
      'view-plans': 'Ver planes',
      'login.title': 'Iniciar sesión',
      'login.email': 'Correo electrónico',
      'login.password': 'Contraseña',
      'login.remember': 'Mantener sesión iniciada',
      'login.button': 'Ingresar',
      'login.forgotPassword': '¿Olvidaste tu contraseña?',
      'login.back': 'Volver al inicio',
      'login.eyebrow': 'Acceso a la plataforma',
      'login.welcome': 'Bienvenido nuevamente.',
      'login.subtitle': 'Ingresá con tus credenciales para continuar gestionando tu equipo.',
      'login.workEmail': 'Email laboral',
      'login.showPassword': 'Mostrar contraseña',
      'login.hidePassword': 'Ocultar contraseña',
      'login.submitting': 'Ingresando…',
      'login.start': '¿Querés empezar a usar TeamBalance?',
      'login.choosePlan': 'Elegí tu plan',
      'login.resend': '¿No recibiste el correo de validación?',
      'login.resendLink': 'Reenviar enlace',
      'login.invalid': 'Ingresá un email válido y tu contraseña.',
      'signup.eyebrow': 'Registro de agencia',
      'signup.verifying': 'Verificando tu contratación.',
      'signup.verifyingText': 'Estamos comprobando que el pago esté aprobado antes de habilitar el acceso inicial.',
      'signup.cannotContinue': 'No podemos continuar',
      'signup.needsApproved': 'El registro necesita una contratación aprobada.',
      'signup.choosePlan': 'Elegir un plan',
      'signup.started': 'Registro iniciado',
      'signup.completed': 'Tu agencia fue registrada.',
      'signup.emailSent': 'El acceso inicial quedó asociado al rol de Dueño. Te enviamos un enlace para confirmar tu correo antes de iniciar sesión.',
      'signup.emailNotSent': 'El acceso inicial quedó asociado al rol de Dueño, pero no pudimos enviar el correo de validación. Podés solicitar un nuevo enlace desde el inicio de sesión.',
      'signup.goSignin': 'Ir a iniciar sesión',
      'signup.resend': 'Reenviar validación',
      'signup.backPlans': 'Volver a los planes',
      'signup.title': 'Completá los datos de acceso.',
      'signup.subtitle': 'Tu contratación fue aprobada. Crearemos el acceso inicial de TeamBalance con el rol de Dueño.',
      'signup.firstName': 'Nombre',
      'signup.lastName': 'Apellido',
      'signup.yourName': 'Tu nombre',
      'signup.yourLastName': 'Tu apellido',
      'signup.minName': 'Ingresá al menos 2 caracteres.',
      'signup.workEmail': 'Email laboral',
      'signup.invalidEmail': 'Ingresá un email laboral válido.',
      'signup.phone': 'Teléfono de contacto',
      'signup.invalidPhone': 'Ingresá un teléfono de contacto válido.',
      'signup.password': 'Contraseña',
      'signup.createPassword': 'Creá una contraseña',
      'signup.passwordHint': 'Usá al menos 8 caracteres, combinando letras y números.',
      'signup.passwordError': 'La contraseña debe cumplir los requisitos indicados.',
      'signup.confirmPassword': 'Confirmar contraseña',
      'signup.repeatPassword': 'Repetí tu contraseña',
      'signup.confirmError': 'Confirmá la contraseña elegida.',
      'signup.creating': 'Creando acceso…',
      'signup.create': 'Crear acceso inicial',
      'signup.haveAccount': '¿Ya tenés una cuenta?',
      'auth.asideLabel': 'Acerca de TeamBalance',
      'auth.smartTeamManagement': 'Gestión inteligente de equipos',
      'auth.agencyOperationsContext': 'La operación de tu agencia, con más contexto.',
      'auth.teamManagementDescription': 'Reuní personas, proyectos y capacidad en una misma vista para tomar mejores decisiones cada día.',
      'auth.teamOverview': 'Panorama del equipo',
      'auth.availableCapacity': 'Capacidad disponible',
      'auth.thisWeekIncrease': '+12% esta semana',
      'auth.activeAlerts': 'Alertas activas',
      'auth.reviewToday': 'Para revisar hoy',
      'auth.product': 'Producto',
      'auth.development': 'Desarrollo',
      'auth.design': 'Diseño',
      'auth.availabilityWorkloadVisible': 'Disponibilidad y carga visible',
      'auth.skillsSeniorityAssignment': 'Skills y seniority para asignar mejor',
      'auth.anticipateIssues': 'Alertas para anticipar desvíos',

      'menu.home': 'Inicio',
      'menu.dashboard': 'Panel',
      'menu.projects': 'Proyectos',
      'menu.employees': 'Empleados',
      'menu.security': 'Seguridad',
      'menu.logout': 'Cerrar sesión',
      'menu.plans': 'Planes',
      'menu.about': 'Nosotros',
      'menu.contact': 'Contacto',
      'menu.calendar': 'Calendario',
      'menu.logs': 'Bitácora',
      'menu.help': 'Ayuda',
      'menu.profile': 'Perfil',
      'menu.tasks': 'Tareas',
      'menu.reports': 'Reportes',
      'menu.agency': 'Configuración de agencia',
      'menu.subscription': 'Suscripción',
      'menu.bestFit': 'Best Fit',
      'menu.teamCalendar': 'Calendario del equipo',
      'menu.simulation': 'Simulación de impacto',
      'menu.myTasks': 'Mis tareas',
      'menu.kanban': 'Tablero Kanban',
      'menu.registerHours': 'Registrar horas',
      'menu.availability': 'Mi disponibilidad',
      'menu.workload': 'Mi carga operativa',
      'menu.roles': 'Roles',
      'menu.plansManagement': 'Gestión de planes',
      'menu.product': 'Producto',
      'menu.company': 'Empresa',
      'menu.legal': 'Legal',
      'menu.terms': 'Términos y condiciones',
      'menu.privacy': 'Política de privacidad',
      'menu.securityPolicy': 'Política de seguridad',

      'footer.description': 'Planificación de capacidad para agencias y consultoras que trabajan por proyectos.',
      'footer.rights': '© 2026 TeamBalance. Todos los derechos reservados.',
      'footer.tagline': 'Gestión inteligente de equipos.',
      'about.eyebrow': 'Sobre TeamBalance',
      'about.title': 'Equipos mejor organizados. Decisiones mejor informadas.',
      'about.lead': 'TeamBalance ayuda a agencias digitales y consultoras a ordenar personas, proyectos y horas sin depender de planillas aisladas.',
      'about.problem.eyebrow': 'El problema que resolvemos',
      'about.problem.title': 'La rentabilidad también se planifica.',
      'about.problem.text1': 'Una asignación incorrecta afecta plazos, costos y bienestar. Sin visibilidad de capacidad, los perfiles críticos se sobrecargan y otros recursos se subutilizan.',
      'about.problem.text2': 'TeamBalance reúne esa información para que dueños y project managers anticipen riesgos y comparen alternativas.',
      'about.mission': 'Misión',
      'about.mission.title': 'Dar claridad para asignar mejor.',
      'about.mission.text': 'Facilitamos la planificación de recursos para que cada proyecto cuente con disponibilidad y perfil adecuados.',
      'about.vision': 'Visión',
      'about.vision.title': 'Equipos más sostenibles.',
      'about.vision.text': 'Buscamos convertir la información operativa en decisiones simples, útiles y responsables.',
      'about.focus': 'Enfoque',
      'about.focus.title': 'Datos que explican una decisión.',
      'about.focus.text': 'Skills, seniority, carga, disponibilidad y plazos aportan contexto sin reemplazar el criterio humano.',
      'about.cta': '¿Tu agencia crece por proyectos?',
      'about.ctaTitle': 'Conversemos sobre una planificación con más contexto.',
      'about.ctaButton': 'Contactarnos',
      'contact.eyebrow': 'Contacto',
      'contact.title': 'Hablemos sobre la capacidad de tu equipo.',
      'contact.lead': 'Contanos cómo se organizan hoy tus proyectos y dónde TeamBalance puede aportar más valor.',
      'contact.asideEyebrow': 'Una conversación útil',
      'contact.asideTitle': 'Para agencias que quieren decidir con más claridad.',
      'contact.asideText': 'Podemos conversar sobre capacidad, asignación por skills, alertas de carga y el plan que mejor acompañe a tu operación.',
      'contact.point1': 'Analizá la situación actual de tu equipo.',
      'contact.point2': 'Conocé las funcionalidades relevantes para tu agencia.',
      'contact.point3': 'Encontrá una forma simple de empezar.',
      'contact.name': 'Nombre',
      'contact.organization': 'Agencia u organización',
      'contact.email': 'Correo electrónico',
      'contact.message': '¿Qué necesitás resolver?',
      'contact.send': 'Enviar consulta',
      'contact.note': 'Usaremos estos datos únicamente para responder a tu consulta y dar seguimiento comercial.',

      'plans.eyebrow': 'Planes TeamBalance',
      'plans.title': 'Una versión para cada etapa de crecimiento.',
      'plans.subtitle': 'Elegí la capacidad adecuada para tu agencia. Todos los planes se contratan mensualmente e incluyen la puesta en marcha básica.',
      'plans.month': 'mes',
      'plans.hire': 'Contratar TeamBalance',
      'plans.compare': 'Comparar planes',
      'plans.hideComparison': 'Ocultar comparación',
      'plans.comparison.title': 'Compará capacidades y funcionalidades',
      'plans.comparison.subtitle': 'Revisá qué incorpora cada modalidad antes de contratar.',
      'plans.comparison.feature': 'Funcionalidad',
      'plans.loadError': 'No pudimos cargar los planes disponibles.',
      'plans.empty': 'No hay planes activos disponibles en este momento.',
      'plans.description.entry': 'Para agencias de hasta 20 usuarios.',
      'plans.description.business': 'Para agencias de 21 a 50 usuarios.',
      'plans.description.corporate': 'Para agencias de 51 a 200 usuarios.',
      'plans.onboarding.eyebrow': 'Incluido en la suscripción',
      'plans.onboarding.title': 'Te acompañamos en la puesta en marcha',
      'plans.onboarding.text': 'La contratación incluye el alta de la cuenta, configuración básica, carga inicial de datos y capacitación inicial para comenzar.',
      'plans.custom.title': '¿Necesitás algo adicional?',
      'plans.custom.text': 'Capacitaciones adicionales, integraciones y adaptaciones específicas se cotizan según el alcance.',
      'plans.custom.cta': 'Consultar servicio',
      'plans.feature.projects-resources': 'Gestión de proyectos y recursos',
      'plans.feature.best-fit': 'Motor Best Fit',
      'plans.feature.dashboards': 'Dashboards operativos',
      'plans.feature.alerts': 'Alertas',
      'plans.feature.standard-reports': 'Reportes estándar',
      'plans.feature.documentation': 'Documentación de uso',
      'plans.feature.standard-support': 'Soporte estándar',
      'plans.feature.updates': 'Actualizaciones del sistema',
      'plans.feature.onboarding': 'Puesta en marcha básica',
      'plans.feature.extended-reports': 'Reportes ampliados',
      'plans.feature.capacity-tracking': 'Seguimiento de capacidad',
      'plans.feature.priority-support': 'Soporte prioritario',
      'plans.feature.adoption-support': 'Acompañamiento inicial de adopción',
      'plans.feature.advanced-analytics': 'Analítica operativa avanzada',
      'plans.feature.reinforced-support': 'Soporte prioritario reforzado',
      'plans.feature.commercial-follow-up': 'Seguimiento comercial y operativo',

      'planManager.eyebrow': 'Administración comercial',
      'planManager.title': 'Gestión de planes',
      'planManager.subtitle': 'Creá, actualizá y administrá la vigencia de los planes que se muestran en la web pública.',
      'planManager.new': 'Nuevo plan',
      'planManager.list': 'Planes configurados',
      'planManager.name': 'Nombre',
      'planManager.description': 'Descripción',
      'planManager.price': 'Precio',
      'planManager.currency': 'Moneda',
      'planManager.periodicity': 'Periodicidad',
      'planManager.duration': 'Duración en meses',
      'planManager.features': 'Funcionalidades',
      'planManager.featuresHelp': 'Separá las funcionalidades con punto y coma (;).',
      'planManager.renewal': 'Condiciones de renovación',
      'planManager.start': 'Vigente desde',
      'planManager.end': 'Vigente hasta',
      'planManager.status': 'Estado',
      'planManager.saved': 'El plan se guardó correctamente.',
      'planManager.error': 'No pudimos completar la operación.',

      'checkout.eyebrow': 'Contratación TeamBalance',
      'checkout.title': 'Completá tu contratación.',
      'checkout.subtitle': 'Ingresá los datos de tu agencia y revisá el plan antes de continuar al pago.',
      'checkout.summary': 'Resumen de compra',
      'checkout.changePlan': 'Cambiar plan',
      'checkout.continue': 'Continuar al pago',
      'checkout.redirecting': 'Estamos redirigiéndote al sitio seguro de pago.',
      'checkout.noPlan': 'Seleccioná un plan antes de continuar.',

      'logs.title': 'Bitácora de actividad y accesos',
      'logs.filters': 'Filtros de búsqueda',
      'logs.date': 'Fecha',
      'logs.agency': 'Agencia',
      'logs.user': 'Usuario',
      'logs.module': 'Módulo',
      'logs.action': 'Acción',
      'logs.result': 'Resultado',
      'logs.criticality': 'Criticidad',
      'logs.subtitle': 'Consultá los eventos registrados y aplicá varios criterios de búsqueda.',
      'logs.from': 'Desde',
      'logs.to': 'Hasta',
      'logs.entity': 'Entidad',
      'logs.clear': 'Limpiar filtros',
      'logs.apply': 'Aplicar filtros',
      'logs.events': 'Eventos registrados',
      'logs.empty': 'No se encontraron eventos con los filtros aplicados.',
      'logs.details': 'Detalle del evento',
      'logs.message': 'Mensaje',
      'logs.error': 'No fue posible consultar la bitácora.',
      'dashboard.eyebrow': 'Panel operativo',
      'dashboard.greeting': 'Buen día',
      'dashboard.summary': 'Este es el resumen de las herramientas y operaciones disponibles para tu rol.',
      'dashboard.session': 'Sesión activa',
      'dashboard.accesses': 'Accesos habilitados',
      'dashboard.activeProjects': 'Proyectos activos',
      'dashboard.inProgress': 'En curso',
      'dashboard.sessionStatus': 'Estado de sesión',
      'dashboard.protected': 'Protegida',
      'dashboard.projects': 'Proyectos',
      'dashboard.manageProjects': 'Gestionar proyectos',
      'dashboard.projectsSubtitle': 'Seguimiento rápido de los proyectos activos de la agencia.',
      'dashboard.newProject': 'Nuevo proyecto',
      'dashboard.hide': 'Ocultar',
      'dashboard.viewProjects': 'Ver proyectos',
      'dashboard.loadingProjects': 'Cargando proyectos…',
      'dashboard.noDescription': 'Sin descripción registrada',
      'dashboard.view': 'Ver',
      'dashboard.emptyProjectsTitle': 'Todavía no hay proyectos activos',
      'dashboard.emptyProjectsText': 'Creá un proyecto para empezar a organizar tareas, responsables y plazos.',
      'dashboard.nextSteps': 'Próximos pasos',
      'dashboard.tools': 'Herramientas de trabajo',
      'dashboard.toolsSubtitle': 'Accesos disponibles según tus permisos.',
      'tasks.eyebrow': 'Planificación',
      'tasks.title': 'Gestión de tareas',
      'tasks.subtitle': 'Definí, ordená y asigná el trabajo de cada proyecto.',
      'tasks.new': 'Nueva tarea',
      'tasks.edit': 'Editar tarea',
      'tasks.newHelp': 'Definí el trabajo a realizar',
      'tasks.skill': 'Skill requerida',
      'tasks.selectSkill': 'Seleccioná una skill',
      'tasks.addSkill': 'Skill',
      'tasks.catalog': 'Catálogo',
      'tasks.skillDialog': 'Skills para tareas',
      'tasks.skillDialogText': 'Creá una skill para usarla inmediatamente en esta tarea.',
      'tasks.availableSkills': 'Skills disponibles',
      'tasks.save': 'Guardar tarea',
      'tasks.planned': 'Tareas planificadas',
      'tasks.emptyTitle': 'Sin tareas todavía',
      'tasks.emptyText': 'Primero registrá un proyecto, creá las skills necesarias y luego organizá sus tareas.',
      'myTasks.eyebrow': 'Mi operación',
      'myTasks.title': 'Mis tareas',
      'myTasks.subtitle': 'Consultá tus pendientes, prioridades y vencimientos en una vista personal.',
      'myTasks.logHours': 'Registrar horas',
      'myTasks.pending': 'Trabajo pendiente',
      'myTasks.pendingHelp': 'Las tareas asignadas a tu usuario aparecen en este panel.',
      'myTasks.loading': 'Cargando tus tareas…',
      'myTasks.emptyTitle': 'Todavía no hay tareas para mostrar',
      'myTasks.emptyText': 'Cuando te asignen una tarea, vas a poder revisar su estado, prioridad y vencimiento desde acá.',
      'myTasks.noDescription': 'Sin descripción',
      'myTasks.due': 'Vence:',
      'myTasks.noDue': 'Sin vencimiento',
      'myTasks.week': 'Mi semana',
      'myTasks.organize': 'Organizá tu trabajo',
      'myTasks.kanbanHelp': 'Usá el tablero Kanban para visualizar el estado de cada tarea asignada.',
      'myTasks.openKanban': 'Abrir tablero Kanban',
      'subscription.eyebrow': 'Suscripción',
      'subscription.title': 'Tu servicio TeamBalance',
      'subscription.subtitle': 'Consultá el estado de tu contratación y encontrá ayuda para administrar el servicio.',
      'subscription.current': 'Estado actual',
      'subscription.info': 'Información de suscripción',
      'subscription.loading': 'Cargando información de la suscripción…',
      'subscription.plan': 'Plan',
      'subscription.status': 'Estado',
      'subscription.amount': 'Importe vigente',
      'subscription.expiration': 'Vencimiento',
      'subscription.renewal': 'Renovación',
      'subscription.reference': 'Referencia',
      'subscription.automatic': 'Automática',
      'subscription.manual': 'Manual',
      'subscription.empty': 'Esta agencia todavía no tiene una suscripción registrada.',
      'subscription.help': '¿Necesitás ayuda?',
      'subscription.helpText': 'Nuestro equipo puede orientarte sobre tu contratación, facturación y adopción de TeamBalance.',
      'subscription.contact': 'Contactar soporte',
      'projects.eyebrow': 'Proyectos',
      'projects.title': 'Gestión de proyectos',
      'projects.subtitle': 'Organizá los proyectos, sus responsables y plazos.',
      'projects.new': 'Nuevo proyecto',
      'employees.eyebrow': 'Agencia',
      'employees.title': 'Gestión de empleados',
      'employees.subtitle': 'Administrá los usuarios, sus roles, skills y disponibilidad base.',
      'employees.new': 'Nuevo usuario',
      'employees.edit': 'Editar usuario',
      'roles.eyebrow': 'Soporte TeamBalance',
      'roles.title': 'Gestión de roles',
      'roles.subtitle': 'Los permisos son rutas estáticas de la plataforma. Los roles agrupan esos permisos y pueden asignarse a uno o varios usuarios.',
      'roles.new': 'Nuevo rol',
      'roles.edit': 'Editar rol',
      'roles.name': 'Nombre',
      'roles.description': 'Descripción',
      'roles.userType': 'Tipo de usuario',
      'roles.userTypeHelp': 'Clasifica el rol para que TeamBalance cree el perfil correspondiente al asignarlo.',
      'roles.permissions': 'Permisos estáticos',
      'roles.save': 'Guardar rol',
      'roles.list': 'Roles configurados',
      'roles.base': 'Rol base',
      'roles.assignedPermissions': 'permisos asignados',
      'roles.owner': 'Dueño',
      'roles.ownerHelp': 'Administración general de una agencia.',
      'roles.pm': 'Project Manager',
      'roles.pmHelp': 'Planificación y gestión operativa.',
      'roles.employee': 'Empleado',
      'roles.employeeHelp': 'Ejecución de tareas y registro operativo.',
      'roles.support': 'Soporte TeamBalance',
      'roles.supportHelp': 'Operación interna de TeamBalance.',
      'profile.eyebrow': 'Cuenta', 'profile.title': 'Mi perfil', 'profile.subtitle': 'Información de la cuenta con la que accedés a TeamBalance.', 'profile.email': 'Correo electrónico', 'profile.mainRole': 'Rol principal', 'profile.userType': 'Tipo de usuario', 'profile.agency': 'Agencia', 'profile.internalTeam': 'Equipo TeamBalance', 'profile.security': 'Seguridad de la cuenta', 'profile.securityText': 'Actualizá tu contraseña y cerrá las sesiones activas por seguridad.', 'profile.missing': 'No encontramos tu información de perfil', 'profile.missingText': 'Volvé a iniciar sesión para actualizar los datos de la cuenta.',
      'security.title': 'Seguridad de la cuenta', 'security.eyebrow': 'Mi cuenta', 'security.change': 'Cambiar contraseña', 'security.help': 'Al confirmar el cambio, se cerrarán las sesiones activas y tendrás que iniciar sesión nuevamente.', 'security.current': 'Contraseña actual', 'security.new': 'Nueva contraseña', 'security.repeat': 'Repetir nueva contraseña', 'security.updating': 'Actualizando…',
      'kanban.eyebrow': 'Mi operación', 'kanban.title': 'Tablero Kanban', 'kanban.subtitle': 'Visualizá el flujo de las tareas que te asignaron por estado.', 'kanban.loading': 'Cargando tablero…', 'kanban.empty': 'Sin tareas en este estado.', 'kanban.noDescription': 'Sin descripción', 'kanban.due': 'Vence:', 'kanban.noDue': 'Sin vencimiento',
    },

    en: {
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.search': 'Search',
      'common.close': 'Close',
      'common.edit': 'Edit',
      'common.create': 'Create',
      'common.update': 'Update',
      'common.active': 'Active',
      'common.inactive': 'Inactive',
      'common.activate': 'Activate',
      'common.deactivate': 'Deactivate',
      'common.loading': 'Loading…',
      'common.retry': 'Try again',
      'common.included': 'Included',
      'common.required': 'Complete this field.',

      'signin': 'Sign in',
      'view-plans': 'View plans',
      'login.title': 'Sign in',
      'login.email': 'Email',
      'login.password': 'Password',
      'login.remember': 'Keep me signed in',
      'login.button': 'Sign in',
      'login.forgotPassword': 'Forgot your password?',
      'login.back': 'Back to home',
      'login.eyebrow': 'Platform access',
      'login.welcome': 'Welcome back.',
      'login.subtitle': 'Sign in with your credentials to continue managing your team.',
      'login.workEmail': 'Work email',
      'login.showPassword': 'Show password',
      'login.hidePassword': 'Hide password',
      'login.submitting': 'Signing in…',
      'login.start': 'Want to start using TeamBalance?',
      'login.choosePlan': 'Choose your plan',
      'login.resend': 'Did not receive the validation email?',
      'login.resendLink': 'Resend link',
      'login.invalid': 'Enter a valid email and your password.',
      'signup.eyebrow': 'Agency registration',
      'signup.verifying': 'Verifying your subscription.',
      'signup.verifyingText': 'We are checking that payment has been approved before enabling the initial access.',
      'signup.cannotContinue': 'We cannot continue',
      'signup.needsApproved': 'Registration requires an approved subscription.',
      'signup.choosePlan': 'Choose a plan',
      'signup.started': 'Registration started',
      'signup.completed': 'Your agency was registered.',
      'signup.emailSent': 'Initial access is associated with the Owner role. We sent you a link to confirm your email before signing in.',
      'signup.emailNotSent': 'Initial access is associated with the Owner role, but we could not send the validation email. You can request a new link from the sign-in page.',
      'signup.goSignin': 'Go to sign in',
      'signup.resend': 'Resend validation',
      'signup.backPlans': 'Back to plans',
      'signup.title': 'Complete your access details.',
      'signup.subtitle': 'Your subscription was approved. We will create the initial TeamBalance access with the Owner role.',
      'signup.firstName': 'First name',
      'signup.lastName': 'Last name',
      'signup.yourName': 'Your first name',
      'signup.yourLastName': 'Your last name',
      'signup.minName': 'Enter at least 2 characters.',
      'signup.workEmail': 'Work email',
      'signup.invalidEmail': 'Enter a valid work email.',
      'signup.phone': 'Contact phone',
      'signup.invalidPhone': 'Enter a valid contact phone number.',
      'signup.password': 'Password',
      'signup.createPassword': 'Create a password',
      'signup.passwordHint': 'Use at least 8 characters, combining letters and numbers.',
      'signup.passwordError': 'The password must meet the listed requirements.',
      'signup.confirmPassword': 'Confirm password',
      'signup.repeatPassword': 'Repeat your password',
      'signup.confirmError': 'Confirm the password you selected.',
      'signup.creating': 'Creating access…',
      'signup.create': 'Create initial access',
      'signup.haveAccount': 'Already have an account?',
      'auth.asideLabel': 'About TeamBalance',
      'auth.smartTeamManagement': 'Smart team management',
      'auth.agencyOperationsContext': 'Your agency’s operations, with more context.',
      'auth.teamManagementDescription': 'Bring people, projects and capacity together in one view to make better decisions every day.',
      'auth.teamOverview': 'Team overview',
      'auth.availableCapacity': 'Available capacity',
      'auth.thisWeekIncrease': '+12% this week',
      'auth.activeAlerts': 'Active alerts',
      'auth.reviewToday': 'To review today',
      'auth.product': 'Product',
      'auth.development': 'Development',
      'auth.design': 'Design',
      'auth.availabilityWorkloadVisible': 'Visibility into availability and workload',
      'auth.skillsSeniorityAssignment': 'Skills and seniority for better assignments',
      'auth.anticipateIssues': 'Alerts to anticipate potential issues',

      'menu.home': 'Home',
      'menu.dashboard': 'Dashboard',
      'menu.projects': 'Projects',
      'menu.employees': 'Employees',
      'menu.security': 'Security',
      'menu.logout': 'Sign out',
      'menu.plans': 'Plans',
      'menu.about': 'About us',
      'menu.contact': 'Contact',
      'menu.calendar': 'Calendar',
      'menu.logs': 'Activity log',
      'menu.help': 'Help',
      'menu.profile': 'Profile',
      'menu.tasks': 'Tasks',
      'menu.reports': 'Reports',
      'menu.agency': 'Agency settings',
      'menu.subscription': 'Subscription',
      'menu.bestFit': 'Best Fit',
      'menu.teamCalendar': 'Team calendar',
      'menu.simulation': 'Impact simulation',
      'menu.myTasks': 'My tasks',
      'menu.kanban': 'Kanban board',
      'menu.registerHours': 'Log hours',
      'menu.availability': 'My availability',
      'menu.workload': 'My workload',
      'menu.roles': 'Roles',
      'menu.plansManagement': 'Plan management',
      'menu.product': 'Product',
      'menu.company': 'Company',
      'menu.legal': 'Legal',
      'menu.terms': 'Terms and conditions',
      'menu.privacy': 'Privacy policy',
      'menu.securityPolicy': 'Security policy',

      'footer.description': 'Capacity planning for project-based agencies and consulting firms.',
      'footer.rights': '© 2026 TeamBalance. All rights reserved.',
      'footer.tagline': 'Intelligent team management.',
      'about.eyebrow': 'About TeamBalance',
      'about.title': 'Better organized teams. Better informed decisions.',
      'about.lead': 'TeamBalance helps digital agencies and consulting firms organize people, projects and hours without relying on isolated spreadsheets.',
      'about.problem.eyebrow': 'The problem we solve',
      'about.problem.title': 'Profitability also needs planning.',
      'about.problem.text1': 'A wrong assignment affects deadlines, costs and well-being. Without visibility into capacity, critical profiles are overloaded and other resources are underused.',
      'about.problem.text2': 'TeamBalance brings this information together so owners and project managers can anticipate risks and compare alternatives.',
      'about.mission': 'Mission',
      'about.mission.title': 'Provide clarity for better assignment.',
      'about.mission.text': 'We simplify resource planning so every project has the right availability and profile.',
      'about.vision': 'Vision',
      'about.vision.title': 'More sustainable teams.',
      'about.vision.text': 'We aim to turn operational information into simple, useful and responsible decisions.',
      'about.focus': 'Approach',
      'about.focus.title': 'Data that explains a decision.',
      'about.focus.text': 'Skills, seniority, workload, availability and deadlines provide context without replacing human judgment.',
      'about.cta': 'Does your agency grow through projects?',
      'about.ctaTitle': 'Let us discuss planning with more context.',
      'about.ctaButton': 'Contact us',
      'contact.eyebrow': 'Contact',
      'contact.title': 'Let us talk about your team capacity.',
      'contact.lead': 'Tell us how your projects are organized today and where TeamBalance can add the most value.',
      'contact.asideEyebrow': 'A useful conversation',
      'contact.asideTitle': 'For agencies that want to decide with greater clarity.',
      'contact.asideText': 'We can discuss capacity planning, skill-based assignments, workload alerts and the plan that best supports your operation.',
      'contact.point1': 'Assess your team’s current situation.',
      'contact.point2': 'Learn about the relevant features for your agency.',
      'contact.point3': 'Find a simple way to get started.',
      'contact.name': 'Name',
      'contact.organization': 'Agency or organization',
      'contact.email': 'Email',
      'contact.message': 'What do you need to solve?',
      'contact.send': 'Send inquiry',
      'contact.note': 'We will use this information only to reply to your inquiry and provide commercial follow-up.',

      'plans.eyebrow': 'TeamBalance plans',
      'plans.title': 'One version for every stage of growth.',
      'plans.subtitle': 'Choose the right capacity for your agency. All plans are billed monthly and include basic onboarding.',
      'plans.month': 'month',
      'plans.hire': 'Get TeamBalance',
      'plans.compare': 'Compare plans',
      'plans.hideComparison': 'Hide comparison',
      'plans.comparison.title': 'Compare capacity and features',
      'plans.comparison.subtitle': 'Review what each option includes before purchasing.',
      'plans.comparison.feature': 'Feature',
      'plans.loadError': 'We could not load the available plans.',
      'plans.empty': 'There are no active plans available right now.',
      'plans.description.entry': 'For agencies with up to 20 users.',
      'plans.description.business': 'For agencies with 21 to 50 users.',
      'plans.description.corporate': 'For agencies with 51 to 200 users.',
      'plans.onboarding.eyebrow': 'Included with your subscription',
      'plans.onboarding.title': 'We support your onboarding',
      'plans.onboarding.text': 'Your subscription includes account setup, basic configuration, initial data loading and initial training.',
      'plans.custom.title': 'Need something else?',
      'plans.custom.text': 'Additional training, integrations and specific adaptations are quoted according to scope.',
      'plans.custom.cta': 'Contact us',
      'plans.feature.projects-resources': 'Project and resource management',
      'plans.feature.best-fit': 'Best Fit engine',
      'plans.feature.dashboards': 'Operational dashboards',
      'plans.feature.alerts': 'Alerts',
      'plans.feature.standard-reports': 'Standard reports',
      'plans.feature.documentation': 'User documentation',
      'plans.feature.standard-support': 'Standard support',
      'plans.feature.updates': 'System updates',
      'plans.feature.onboarding': 'Basic onboarding',
      'plans.feature.extended-reports': 'Extended reports',
      'plans.feature.capacity-tracking': 'Capacity tracking',
      'plans.feature.priority-support': 'Priority support',
      'plans.feature.adoption-support': 'Initial adoption support',
      'plans.feature.advanced-analytics': 'Advanced operational analytics',
      'plans.feature.reinforced-support': 'Enhanced priority support',
      'plans.feature.commercial-follow-up': 'Commercial and operational follow-up',

      'planManager.eyebrow': 'Commercial administration',
      'planManager.title': 'Plan management',
      'planManager.subtitle': 'Create, update and manage the availability of plans shown on the public website.',
      'planManager.new': 'New plan',
      'planManager.list': 'Configured plans',
      'planManager.name': 'Name',
      'planManager.description': 'Description',
      'planManager.price': 'Price',
      'planManager.currency': 'Currency',
      'planManager.periodicity': 'Billing period',
      'planManager.duration': 'Duration in months',
      'planManager.features': 'Features',
      'planManager.featuresHelp': 'Separate features with a semicolon (;).',
      'planManager.renewal': 'Renewal conditions',
      'planManager.start': 'Available from',
      'planManager.end': 'Available until',
      'planManager.status': 'Status',
      'planManager.saved': 'The plan was saved successfully.',
      'planManager.error': 'We could not complete the operation.',

      'checkout.eyebrow': 'TeamBalance subscription',
      'checkout.title': 'Complete your subscription.',
      'checkout.subtitle': 'Enter your agency details and review the plan before continuing to payment.',
      'checkout.summary': 'Order summary',
      'checkout.changePlan': 'Change plan',
      'checkout.continue': 'Continue to payment',
      'checkout.redirecting': 'We are redirecting you to the secure payment site.',
      'checkout.noPlan': 'Select a plan before continuing.',

      'logs.title': 'Activity and access log',
      'logs.filters': 'Search filters',
      'logs.date': 'Date',
      'logs.agency': 'Agency',
      'logs.user': 'User',
      'logs.module': 'Module',
      'logs.action': 'Action',
      'logs.result': 'Result',
      'logs.criticality': 'Criticality',
      'logs.subtitle': 'Review recorded events and combine multiple search criteria.',
      'logs.from': 'From',
      'logs.to': 'To',
      'logs.entity': 'Entity',
      'logs.clear': 'Clear filters',
      'logs.apply': 'Apply filters',
      'logs.events': 'Recorded events',
      'logs.empty': 'No events matched the selected filters.',
      'logs.details': 'Event details',
      'logs.message': 'Message',
      'logs.error': 'The activity log could not be loaded.',
      'dashboard.eyebrow': 'Operations dashboard',
      'dashboard.greeting': 'Good morning',
      'dashboard.summary': 'This is a summary of the tools and operations available for your role.',
      'dashboard.session': 'Active session',
      'dashboard.accesses': 'Enabled access',
      'dashboard.activeProjects': 'Active projects',
      'dashboard.inProgress': 'In progress',
      'dashboard.sessionStatus': 'Session status',
      'dashboard.protected': 'Protected',
      'dashboard.projects': 'Projects',
      'dashboard.manageProjects': 'Manage projects',
      'dashboard.projectsSubtitle': 'Quick monitoring of the agency’s active projects.',
      'dashboard.newProject': 'New project',
      'dashboard.hide': 'Hide',
      'dashboard.viewProjects': 'View projects',
      'dashboard.loadingProjects': 'Loading projects…',
      'dashboard.noDescription': 'No description recorded',
      'dashboard.view': 'View',
      'dashboard.emptyProjectsTitle': 'There are no active projects yet',
      'dashboard.emptyProjectsText': 'Create a project to start organizing tasks, owners and deadlines.',
      'dashboard.nextSteps': 'Next steps',
      'dashboard.tools': 'Work tools',
      'dashboard.toolsSubtitle': 'Available access according to your permissions.',
      'tasks.eyebrow': 'Planning',
      'tasks.title': 'Task management',
      'tasks.subtitle': 'Define, prioritize and assign each project’s work.',
      'tasks.new': 'New task',
      'tasks.edit': 'Edit task',
      'tasks.newHelp': 'Define the work to be done',
      'tasks.skill': 'Required skill',
      'tasks.selectSkill': 'Select a skill',
      'tasks.addSkill': 'Skill',
      'tasks.catalog': 'Catalog',
      'tasks.skillDialog': 'Task skills',
      'tasks.skillDialogText': 'Create a skill to use it immediately in this task.',
      'tasks.availableSkills': 'Available skills',
      'tasks.save': 'Save task',
      'tasks.planned': 'Planned tasks',
      'tasks.emptyTitle': 'There are no tasks yet',
      'tasks.emptyText': 'First register a project, create the needed skills and then organize its tasks.',
      'myTasks.eyebrow': 'My operation',
      'myTasks.title': 'My tasks',
      'myTasks.subtitle': 'Review your pending work, priorities and due dates in one personal view.',
      'myTasks.logHours': 'Log hours',
      'myTasks.pending': 'Pending work',
      'myTasks.pendingHelp': 'Tasks assigned to your user appear in this panel.',
      'myTasks.loading': 'Loading your tasks…',
      'myTasks.emptyTitle': 'There are no tasks to show yet',
      'myTasks.emptyText': 'When a task is assigned to you, you will be able to review its status, priority and due date here.',
      'myTasks.noDescription': 'No description',
      'myTasks.due': 'Due:',
      'myTasks.noDue': 'No due date',
      'myTasks.week': 'My week',
      'myTasks.organize': 'Organize your work',
      'myTasks.kanbanHelp': 'Use the Kanban board to visualize the status of every task assigned to you.',
      'myTasks.openKanban': 'Open Kanban board',
      'subscription.eyebrow': 'Subscription',
      'subscription.title': 'Your TeamBalance service',
      'subscription.subtitle': 'Review your subscription status and find help managing the service.',
      'subscription.current': 'Current status',
      'subscription.info': 'Subscription information',
      'subscription.loading': 'Loading subscription information…',
      'subscription.plan': 'Plan',
      'subscription.status': 'Status',
      'subscription.amount': 'Current amount',
      'subscription.expiration': 'Expiration',
      'subscription.renewal': 'Renewal',
      'subscription.reference': 'Reference',
      'subscription.automatic': 'Automatic',
      'subscription.manual': 'Manual',
      'subscription.empty': 'This agency does not have a subscription registered yet.',
      'subscription.help': 'Need help?',
      'subscription.helpText': 'Our team can guide you through your subscription, billing and TeamBalance adoption.',
      'subscription.contact': 'Contact support',
      'projects.eyebrow': 'Projects',
      'projects.title': 'Project management',
      'projects.subtitle': 'Organize projects, their owners and deadlines.',
      'projects.new': 'New project',
      'employees.eyebrow': 'Agency',
      'employees.title': 'Employee management',
      'employees.subtitle': 'Manage users, their roles, skills and base availability.',
      'employees.new': 'New user',
      'employees.edit': 'Edit user',
      'roles.eyebrow': 'TeamBalance support',
      'roles.title': 'Role management',
      'roles.subtitle': 'Permissions are static platform routes. Roles group those permissions and can be assigned to one or more users.',
      'roles.new': 'New role',
      'roles.edit': 'Edit role',
      'roles.name': 'Name',
      'roles.description': 'Description',
      'roles.userType': 'User type',
      'roles.userTypeHelp': 'Classify the role so TeamBalance creates the corresponding profile when assigning it.',
      'roles.permissions': 'Static permissions',
      'roles.save': 'Save role',
      'roles.list': 'Configured roles',
      'roles.base': 'Base role',
      'roles.assignedPermissions': 'assigned permissions',
      'roles.owner': 'Owner',
      'roles.ownerHelp': 'General administration of an agency.',
      'roles.pm': 'Project Manager',
      'roles.pmHelp': 'Planning and operational management.',
      'roles.employee': 'Employee',
      'roles.employeeHelp': 'Task execution and operational records.',
      'roles.support': 'TeamBalance support',
      'roles.supportHelp': 'Internal TeamBalance operations.',
      'profile.eyebrow': 'Account', 'profile.title': 'My profile', 'profile.subtitle': 'Account information used to access TeamBalance.', 'profile.email': 'Email', 'profile.mainRole': 'Primary role', 'profile.userType': 'User type', 'profile.agency': 'Agency', 'profile.internalTeam': 'TeamBalance team', 'profile.security': 'Account security', 'profile.securityText': 'Update your password and close active sessions for security.', 'profile.missing': 'We could not find your profile information', 'profile.missingText': 'Sign in again to refresh your account information.',
      'security.title': 'Account security', 'security.eyebrow': 'My account', 'security.change': 'Change password', 'security.help': 'When you confirm the change, active sessions will be closed and you will need to sign in again.', 'security.current': 'Current password', 'security.new': 'New password', 'security.repeat': 'Repeat new password', 'security.updating': 'Updating…',
      'kanban.eyebrow': 'My operation', 'kanban.title': 'Kanban board', 'kanban.subtitle': 'Visualize the flow of tasks assigned to you by status.', 'kanban.loading': 'Loading board…', 'kanban.empty': 'No tasks in this status.', 'kanban.noDescription': 'No description', 'kanban.due': 'Due:', 'kanban.noDue': 'No due date',
    }
  };

  readonly language = signal<LanguageCode>((localStorage.getItem('language') as LanguageCode) || 'es');

  readonly culture = signal<CultureCode>((localStorage.getItem('culture') as CultureCode) || 'es-AR');

  cambiarIdioma(language: LanguageCode): void {
    this.language.set(language);
    const culture: CultureCode = language === 'es' ? 'es-AR' : 'en-US';
    this.culture.set(culture);
    localStorage.setItem('language', language);
    localStorage.setItem('culture', culture);
  }

  traducir(key: string, language: LanguageCode = this.language(), fallback?: string): string {
    return this.translations[language][key] ?? fallback ?? key;
  }

  formatearFecha(fecha: Date | string): string {
    return new Intl.DateTimeFormat( this.culture(), { year: 'numeric', month: '2-digit', day: '2-digit',}).format(new Date(fecha));
  }

  formatearFechaHora(fecha: Date | string): string {
    return new Intl.DateTimeFormat(this.culture(), { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit',}).format(new Date(fecha));
  }

  formatearNumero(numero: number): string {

    return new Intl.NumberFormat(
      this.culture()
    ).format(numero);
  }

  formatearMoneda( monto: number, moneda: string = 'USD'): string {
    return new Intl.NumberFormat( this.culture(), { style: 'currency', currency: moneda,}).format(monto);
  }

}
