import { Injectable, signal } from '@angular/core';

export type LanguageCode = 'es' | 'en';
export type CultureCode = 'es-AR' | 'en-US';

type TranslationDictionary = Record<string, string>;

@Injectable({
  providedIn: 'root',
})
export class LocalizationService {

  private readonly translations: Record<LanguageCode, TranslationDictionary> = {

    es: {
      'common.save': 'Guardar',
      'common.cancel': 'Cancelar',
      'common.search': 'Buscar',
      'common.close': 'Cerrar',
      'common.edit': 'Editar',
      'common.create': 'Crear',
      'common.update': 'Actualizar',
      'common.active': 'Activo',
      'common.inactive': 'Inactivo',
      'common.activate': 'Activar',
      'common.deactivate': 'Dar de baja',
      'common.loading': 'Cargando…',
      'common.retry': 'Reintentar',
      'common.included': 'Incluido',
      'common.required': 'Completá este campo.',

      'faq.kicker': 'Servicio de ayuda', 'faq.title': 'Preguntas frecuentes', 'faq.description': 'Encontrá respuestas rápidas sobre el uso diario de TeamBalance. Esta guía se actualiza junto con las funciones de la plataforma.', 'faq.searchLabel': 'Buscá una respuesta', 'faq.searchPlaceholder': 'Ej.: registrar horas, disponibilidad o suscripción', 'faq.answerFound': 'respuesta encontrada', 'faq.answersFound': 'respuestas encontradas', 'faq.filterLabel': 'Filtrar preguntas por categoría', 'faq.listLabel': 'Listado de preguntas frecuentes', 'faq.emptyTitle': 'No encontramos una respuesta con esa búsqueda.', 'faq.emptyText': 'Probá con otra palabra o consultá al responsable de tu agencia.', 'faq.needHelpKicker': '¿Seguís necesitando ayuda?', 'faq.needHelpTitle': 'Abrí una consulta de soporte', 'faq.needHelpDescription': 'El HelpDesk permite dejar una consulta y continuar la conversación cuando Soporte responda. No compartas contraseñas, códigos de verificación ni información de tarjetas.', 'faq.openSupport': 'Ir a HelpDesk', 'faq.configureNewsletter': 'Configurar newsletter', 'faq.category.all': 'Todas', 'faq.category.firstSteps': 'Primeros pasos', 'faq.category.projects': 'Proyectos y tareas', 'faq.category.team': 'Equipo y disponibilidad', 'faq.category.account': 'Cuenta y suscripción', 'faq.access.question': '¿Cómo sé qué opciones puedo usar?', 'faq.access.answer': 'Las opciones disponibles dependen de tu rol y de los permisos asignados. Si necesitás una función que no aparece, consultá a la persona responsable de tu agencia.', 'faq.project.question': '¿Cómo creo y planifico una tarea?', 'faq.project.answer': 'Desde Proyectos, el PM carga los datos de la tarea y puede asignar un responsable o pedir una sugerencia mediante Best Fit.', 'faq.kanban.question': '¿Cómo actualizo el estado o el avance de una tarea?', 'faq.kanban.answer': 'Abrí la tarea desde el tablero Kanban. En el detalle podés cambiar el estado, marcar subtareas y registrar comentarios.', 'faq.hours.question': '¿Por qué no puedo registrar horas para una fecha?', 'faq.hours.answer': 'El registro debe respetar la ventana de días habilitada, no admite fechas futuras y sólo permite tareas disponibles para tu usuario.', 'faq.bestFit.question': '¿Qué analiza la sugerencia Best Fit?', 'faq.bestFit.answer': 'Best Fit compara skills requeridos, seniority, disponibilidad y carga operativa. Es una recomendación: no asigna ni mueve automáticamente a nadie.', 'faq.availability.question': '¿Cómo informo una ausencia o cambio de disponibilidad?', 'faq.availability.answer': 'Desde Mi disponibilidad podés mantener tu horario base y registrar licencias o ausencias cuando corresponda.', 'faq.skills.question': '¿Para qué sirven los skills y el seniority?', 'faq.skills.answer': 'Los skills describen capacidades concretas y el seniority indica el nivel recomendado para una tarea.', 'faq.subscription.question': '¿Cómo gestiono la suscripción de mi agencia?', 'faq.subscription.answer': 'El Dueño consulta el plan vigente, historial y renovación desde Configuración de agencia > Suscripción.', 'faq.security.question': '¿Cómo protejo mi cuenta?', 'faq.security.answer': 'No compartas credenciales ni códigos de verificación. Usá una contraseña segura y reportá accesos inesperados.',
      'helpdesk.kicker': 'Servicio de ayuda', 'helpdesk.title': 'Soporte asincrónico', 'helpdesk.description': 'Registrá una consulta y seguí la respuesta del equipo de Soporte.', 'helpdesk.backoffice': 'Soporte TeamBalance', 'helpdesk.inboxTitle': 'Bandeja de soporte', 'helpdesk.inboxDescription': 'Revisá consultas de usuarios, respondé y mantené actualizado su estado.', 'helpdesk.newTicket': 'Nueva consulta', 'helpdesk.question': '¿En qué podemos ayudarte?', 'helpdesk.category': 'Categoría', 'helpdesk.subject': 'Asunto', 'helpdesk.subjectPlaceholder': 'Ej.: No puedo acceder al tablero', 'helpdesk.descriptionLabel': 'Descripción', 'helpdesk.descriptionPlaceholder': 'Indicá qué estabas haciendo y qué necesitás resolver.', 'helpdesk.sensitiveWarning': 'No incluyas contraseñas, códigos de verificación ni datos de tarjetas.', 'helpdesk.creating': 'Creando…', 'helpdesk.create': 'Crear consulta', 'helpdesk.followUp': 'Seguimiento', 'helpdesk.myTickets': 'Mis consultas', 'helpdesk.inbox': 'Bandeja', 'helpdesk.customerTickets': 'Consultas de usuarios', 'helpdesk.noAgency': 'Sin agencia', 'helpdesk.messages': 'mensaje(s)', 'helpdesk.myTicketsEmpty': 'Todavía no registraste consultas de soporte.', 'helpdesk.inboxEmpty': 'No hay consultas pendientes de atención.', 'helpdesk.status': 'Estado', 'helpdesk.service': 'Servicio TeamBalance', 'helpdesk.resolve': 'Marcar como resuelta', 'helpdesk.changeStatus': 'Actualizar estado', 'helpdesk.saveStatus': 'Guardar estado', 'helpdesk.you': 'Vos', 'helpdesk.team': 'Soporte TeamBalance', 'helpdesk.reply': 'Respuesta para el usuario', 'helpdesk.addInfo': 'Agregar información', 'helpdesk.sending': 'Enviando…', 'helpdesk.send': 'Enviar mensaje', 'helpdesk.selectTicket': 'Seleccioná una consulta para ver la conversación y su seguimiento.', 'helpdesk.created': 'Consulta creada correctamente. Soporte responderá de forma asincrónica.', 'helpdesk.loadError': 'No pudimos cargar las consultas.', 'helpdesk.createError': 'No se pudo crear la consulta.', 'helpdesk.detailError': 'No pudimos abrir la consulta.', 'helpdesk.sendError': 'No se pudo enviar el mensaje.', 'helpdesk.statusSaved': 'Estado actualizado correctamente.', 'helpdesk.statusError': 'No se pudo actualizar el estado.', 'helpdesk.resolved': 'Consulta marcada como resuelta.', 'helpdesk.category.Acceso': 'Acceso', 'helpdesk.category.Usuarios': 'Usuarios', 'helpdesk.category.Funcionalidad': 'Funcionalidad', 'helpdesk.category.Suscripción y pagos': 'Suscripción y pagos', 'helpdesk.category.Otro': 'Otro', 'helpdesk.status.Pendiente': 'Pendiente', 'helpdesk.status.En revisión': 'En revisión', 'helpdesk.status.Respondida': 'Respondida', 'helpdesk.status.Resuelta': 'Resuelta',
      'news.kicker': 'Comunicaciones', 'news.preferencesTitle': 'Novedades por email', 'news.preferencesDescription': 'Elegí qué comunicaciones querés recibir y cambialas cuando quieras.', 'news.backoffice': 'Comunicaciones', 'news.managementTitle': 'Gestión de novedades', 'news.managementDescription': 'Publicá comunicaciones y administrá su vigencia sin recibir newsletters.', 'news.newsletterKicker': 'Newsletter', 'news.myCategories': 'Mis categorías', 'news.preferencesHint': 'Las noticias públicas siguen disponibles en la web; estas preferencias sólo definen qué categorías llegan a tu email.', 'news.savePreferences': 'Guardar preferencias', 'news.publishKicker': 'Backoffice de Soporte', 'news.publishTitle': 'Publicar una novedad', 'news.category': 'Categoría', 'news.selectCategory': 'Seleccionar categoría', 'news.newsTitle': 'Título', 'news.content': 'Contenido', 'news.imageUrl': 'URL de imagen (opcional)', 'news.publicationDate': 'Publicación', 'news.expirationDate': 'Vencimiento', 'news.publishHint': 'Si no indicás fecha de publicación se publica ahora. Al vencerse, deja de verse en la página pública.', 'news.publishing': 'Publicando…', 'news.publishAndSend': 'Publicar y enviar newsletter', 'news.historyKicker': 'Historial', 'news.historyTitle': 'Novedades administradas', 'news.publishedAt': 'Publicación', 'news.sent': 'Newsletter procesado', 'news.pending': 'Pendiente de envío', 'news.historyEmpty': 'Todavía no hay novedades publicadas.', 'news.loadError': 'No pudimos cargar las novedades.', 'news.preferencesSaved': 'Preferencias de newsletter guardadas correctamente.', 'news.preferencesError': 'No se pudieron guardar las preferencias.', 'news.published': 'Novedad publicada. Se enviará por email a quienes estén suscriptos a la categoría.', 'news.publishError': 'No se pudo publicar la novedad.', 'news.deactivated': 'Novedad dada de baja correctamente.', 'news.deactivateError': 'No se pudo dar de baja la novedad.',

      'signin': 'Iniciar sesión',
      'view-plans': 'Ver planes',
      'login.title': 'Iniciar sesión',
      'login.email': 'Correo electrónico',
      'login.password': 'Contraseña',
      'login.remember': 'Mantener sesión iniciada',
      'login.button': 'Ingresar',
      'login.forgotPassword': '¿Olvidaste tu contraseña?',
      'login.back': 'Volver al inicio',
      'login.eyebrow': 'Acceso a la plataforma',
      'login.welcome': 'Bienvenido nuevamente.',
      'login.subtitle': 'Ingresá con tus credenciales para continuar gestionando tu equipo.',
      'login.workEmail': 'Email laboral',
      'login.showPassword': 'Mostrar contraseña',
      'login.hidePassword': 'Ocultar contraseña',
      'login.submitting': 'Ingresando…',
      'login.start': '¿Querés empezar a usar TeamBalance?',
      'login.choosePlan': 'Elegí tu plan',
      'login.resend': '¿No recibiste el correo de validación?',
      'login.resendLink': 'Reenviar enlace',
      'login.invalid': 'Ingresá un email válido y tu contraseña.',
      'signup.eyebrow': 'Registro de agencia',
      'signup.verifying': 'Verificando tu contratación.',
      'signup.verifyingText': 'Estamos comprobando que el pago esté aprobado antes de habilitar el acceso inicial.',
      'signup.cannotContinue': 'No podemos continuar',
      'signup.needsApproved': 'El registro necesita una contratación aprobada.',
      'signup.choosePlan': 'Elegir un plan',
      'signup.started': 'Registro iniciado',
      'signup.completed': 'Tu agencia fue registrada.',
      'signup.emailSent': 'El acceso inicial quedó asociado al rol de Dueño. Te enviamos un enlace para confirmar tu correo antes de iniciar sesión.',
      'signup.emailNotSent': 'El acceso inicial quedó asociado al rol de Dueño, pero no pudimos enviar el correo de validación. Podés solicitar un nuevo enlace desde el inicio de sesión.',
      'signup.goSignin': 'Ir a iniciar sesión',
      'signup.resend': 'Reenviar validación',
      'signup.backPlans': 'Volver a los planes',
      'signup.title': 'Completá los datos de acceso.',
      'signup.subtitle': 'Tu contratación fue aprobada. Crearemos el acceso inicial de TeamBalance con el rol de Dueño.',
      'signup.firstName': 'Nombre',
      'signup.lastName': 'Apellido',
      'signup.yourName': 'Tu nombre',
      'signup.yourLastName': 'Tu apellido',
      'signup.minName': 'Ingresá al menos 2 caracteres.',
      'signup.workEmail': 'Email laboral',
      'signup.invalidEmail': 'Ingresá un email laboral válido.',
      'signup.phone': 'Teléfono de contacto',
      'signup.invalidPhone': 'Ingresá un teléfono de contacto válido.',
      'signup.password': 'Contraseña',
      'signup.createPassword': 'Creá una contraseña',
      'signup.passwordHint': 'Usá al menos 8 caracteres, combinando letras y números.',
      'signup.passwordError': 'La contraseña debe cumplir los requisitos indicados.',
      'signup.confirmPassword': 'Confirmar contraseña',
      'signup.repeatPassword': 'Repetí tu contraseña',
      'signup.confirmError': 'Confirmá la contraseña elegida.',
      'signup.termsPrefix': 'Leí y acepto los', 'signup.termsLink': 'Términos y Condiciones', 'signup.termsSuffix': 'de TeamBalance.', 'signup.termsError': 'Necesitás aceptar los Términos y Condiciones para completar el registro.',
      'signup.newsletterOptIn': 'Quiero recibir novedades de TeamBalance por email.',
      'signup.newsletterCategoriesHint': 'Elegí las categorías que te interesan. Podés cambiarlas cuando quieras.',
      'signup.newsletterCategoryRequired': 'Elegí al menos una categoría o desmarcá la suscripción a novedades.',
      'signup.creating': 'Creando acceso…',
      'signup.create': 'Crear acceso inicial',
      'signup.haveAccount': '¿Ya tenés una cuenta?',
      'auth.asideLabel': 'Acerca de TeamBalance',
      'auth.smartTeamManagement': 'Gestión inteligente de equipos',
      'auth.agencyOperationsContext': 'La operación de tu agencia, con más contexto.',
      'auth.teamManagementDescription': 'Reuní personas, proyectos y capacidad en una misma vista para tomar mejores decisiones cada día.',
      'auth.teamOverview': 'Panorama del equipo',
      'auth.availableCapacity': 'Capacidad disponible',
      'auth.thisWeekIncrease': '+12% esta semana',
      'auth.activeAlerts': 'Alertas activas',
      'auth.reviewToday': 'Para revisar hoy',
      'auth.product': 'Producto',
      'auth.development': 'Desarrollo',
      'auth.design': 'Diseño',
      'auth.availabilityWorkloadVisible': 'Disponibilidad y carga visible',
      'auth.skillsSeniorityAssignment': 'Skills y seniority para asignar mejor',
      'auth.anticipateIssues': 'Alertas para anticipar desvíos',

      'menu.home': 'Inicio',
      'menu.dashboard': 'Panel',
      'menu.projects': 'Proyectos',
      'menu.employees': 'Empleados',
      'menu.security': 'Seguridad',
      'menu.logout': 'Cerrar sesión',
      'menu.plans': 'Planes',
      'menu.about': 'Nosotros',
      'menu.contact': 'Contacto',
      'menu.calendar': 'Calendario',
      'menu.logs': 'Bitácora',
      'menu.help': 'Ayuda',
      'menu.support': 'Soporte',
      'menu.newsletter': 'Novedades por email',
      'menu.supportInbox': 'Bandeja de soporte',
      'menu.newsManagement': 'Gestión de novedades',
      'menu.operators': 'Operadores',
      'menu.backups': 'Respaldos',
      'menu.profile': 'Perfil',
      'menu.tasks': 'Tareas',
      'menu.reports': 'Reportes',
      'menu.agency': 'Configuración de agencia',
      'menu.subscription': 'Suscripción',
      'menu.bestFit': 'Best Fit',
      'menu.teamCalendar': 'Calendario del equipo',
      'menu.simulation': 'Simulación de impacto',
      'menu.skillsCoverage': 'Cobertura de skills',
      'menu.templates': 'Plantillas de tareas',
      'menu.myTasks': 'Mis tareas',
      'menu.kanban': 'Tablero Kanban',
      'menu.registerHours': 'Registrar horas',
      'menu.availability': 'Mi disponibilidad',
      'menu.workload': 'Mi carga operativa',
      'menu.roles': 'Roles',
      'menu.plansManagement': 'Gestión de planes',
      'operators.kicker': 'BackOffice TeamBalance',
      'operators.title': 'Gestión de operadores',
      'operators.description': 'Creá, actualizá, activá o da de baja usuarios internos de Soporte. No pertenecen a ninguna agencia y sólo reciben roles internos.',
      'operators.new': 'Nuevo operador',
      'operators.newTitle': 'Nuevo operador',
      'operators.editTitle': 'Editar operador',
      'operators.firstName': 'Nombre',
      'operators.lastName': 'Apellido',
      'operators.email': 'Email laboral',
      'operators.password': 'Contraseña temporal',
      'operators.passwordOptional': 'Contraseña temporal (opcional)',
      'operators.passwordHint': 'La persona deberá validar su correo antes de iniciar sesión.',
      'operators.passwordEditHint': 'Dejala vacía para conservar la contraseña actual.',
      'operators.roles': 'Roles internos',
      'operators.roleRequired': 'Seleccioná al menos un rol interno de Soporte.',
      'operators.required': 'Completá los datos obligatorios.',
      'operators.create': 'Crear operador',
      'operators.list': 'Operadores registrados',
      'operators.listHelp': 'Los cambios de estado no eliminan registros ni afectan a usuarios de agencias.',
      'operators.empty': 'Todavía no hay operadores internos registrados.',
      'operators.created': 'Operador creado correctamente. Se envió la validación por email.',
      'operators.updated': 'Operador actualizado correctamente.',
      'operators.activated': 'Operador activado correctamente.',
      'operators.deactivated': 'Operador dado de baja correctamente.',
      'operators.loadError': 'No pudimos cargar los operadores internos.',
      'operators.saveError': 'No pudimos guardar el operador.',
      'operators.statusError': 'No pudimos actualizar el estado del operador.',
      'backup.kicker': 'Continuidad operativa',
      'backup.title': 'Respaldo y restauración',
      'backup.description': 'Administrá copias completas de la base de datos. Los respaldos se verifican antes de quedar disponibles y las pruebas de restauración se realizan en una base aislada.',
      'backup.rpo': 'Objetivo de punto de recuperación',
      'backup.rpoHelp': 'Máxima pérdida de información aceptada.',
      'backup.rto': 'Objetivo de tiempo de recuperación',
      'backup.rtoHelp': 'Tiempo máximo previsto para recuperar el servicio.',
      'backup.retention': 'Retención',
      'backup.retentionHelp': 'Las copias vencidas se depuran de forma controlada.',
      'backup.days': 'días',
      'backup.createTitle': 'Crear respaldo completo',
      'backup.createHelp': 'Genera una copia SQL Server con checksum, ejecuta RESTORE VERIFYONLY y conserva una copia de los archivos de configuración declarados.',
      'backup.create': 'Crear respaldo ahora',
      'backup.running': 'Procesando…',
      'backup.created': 'El respaldo se generó y verificó correctamente.',
      'backup.createError': 'No pudimos crear el respaldo. Revisá los permisos de SQL Server sobre la carpeta configurada.',
      'backup.loadError': 'No pudimos cargar el historial de respaldos.',
      'backup.historyTitle': 'Historial de respaldos',
      'backup.historyHelp': 'Solo las copias completas y verificadas pueden usarse para una prueba de restauración.',
      'backup.empty': 'Todavía no se registraron respaldos.',
      'backup.sizeUnavailable': 'Tamaño no disponible',
      'backup.testRestore': 'Probar restauración',
      'backup.restoreKicker': 'Entorno aislado',
      'backup.restoreTitle': 'Probar restauración sin afectar TeamBalance',
      'backup.restoreHelp': 'Se restaurará una copia temporal en una base separada, se ejecutará una comprobación de integridad, se registrará el resultado y luego se eliminará esa base. No modifica la base productiva.',
      'backup.restore': 'Restaurar en aislado',
      'backup.restoreComplete': 'La prueba de restauración aislada finalizó correctamente.',
      'backup.restoreError': 'No pudimos completar la prueba de restauración aislada.',
      'backup.productionRestoreKicker': 'Recuperación de contingencia',
      'backup.productionRestoreTitle': 'Restaurar la base productiva',
      'backup.productionRestoreHelp': 'Esta acción reemplaza TeamBalance por la copia seleccionada. Se desconectarán los usuarios y se perderán los cambios posteriores a la fecha del backup. Usala únicamente ante un incidente real.',
      'backup.productionRestore': 'Recuperar producción',
      'backup.productionRestoreError': 'No pudimos recuperar la base productiva. La aplicación intentó reabrir la base para mantener el acceso disponible.',
      'backup.xmlKicker': 'Auditoría externa',
      'backup.xmlTitle': 'Historial de continuidad',
      'backup.xmlHelp': 'Registro externo XML, independiente de TeamBalance. Conserva eventos de backup y restore aun cuando se recupere la base productiva.',
      'backup.xmlEmpty': 'Todavía no hay eventos registrados en el historial XML externo.',
      'backup.xmlType.Backup': 'Respaldo de base de datos',
      'backup.xmlType.RestoreAislado': 'Prueba de restauración aislada',
      'backup.xmlType.RestoreProduccion': 'Recuperación de producción',
      'menu.product': 'Producto',
      'menu.company': 'Empresa',
      'menu.legal': 'Legal',
      'menu.terms': 'Términos y condiciones',
      'menu.privacy': 'Política de privacidad',
      'menu.securityPolicy': 'Política de seguridad',

      'footer.description': 'Planificación de capacidad para agencias y consultoras que trabajan por proyectos.',
      'footer.rights': '© 2026 TeamBalance. Todos los derechos reservados.',
      'footer.tagline': 'Gestión inteligente de equipos.',
      'about.eyebrow': 'Sobre TeamBalance',
      'about.title': 'Equipos mejor organizados. Decisiones mejor informadas.',
      'about.lead': 'TeamBalance ayuda a agencias digitales y consultoras a ordenar personas, proyectos y horas sin depender de planillas aisladas.',
      'about.problem.eyebrow': 'El problema que resolvemos',
      'about.problem.title': 'La rentabilidad también se planifica.',
      'about.problem.text1': 'Una asignación incorrecta afecta plazos, costos y bienestar. Sin visibilidad de capacidad, los perfiles críticos se sobrecargan y otros recursos se subutilizan.',
      'about.problem.text2': 'TeamBalance reúne esa información para que dueños y project managers anticipen riesgos y comparen alternativas.',
      'about.mission': 'Misión',
      'about.mission.title': 'Dar claridad para asignar mejor.',
      'about.mission.text': 'Facilitamos la planificación de recursos para que cada proyecto cuente con disponibilidad y perfil adecuados.',
      'about.vision': 'Visión',
      'about.vision.title': 'Equipos más sostenibles.',
      'about.vision.text': 'Buscamos convertir la información operativa en decisiones simples, útiles y responsables.',
      'about.focus': 'Enfoque',
      'about.focus.title': 'Datos que explican una decisión.',
      'about.focus.text': 'Skills, seniority, carga, disponibilidad y plazos aportan contexto sin reemplazar el criterio humano.',
      'about.cta': '¿Tu agencia crece por proyectos?',
      'about.ctaTitle': 'Conversemos sobre una planificación con más contexto.',
      'about.ctaButton': 'Contactarnos',
      'contact.eyebrow': 'Contacto',
      'contact.title': 'Hablemos sobre la capacidad de tu equipo.',
      'contact.lead': 'Contanos cómo se organizan hoy tus proyectos y dónde TeamBalance puede aportar más valor.',
      'contact.asideEyebrow': 'Una conversación útil',
      'contact.asideTitle': 'Para agencias que quieren decidir con más claridad.',
      'contact.asideText': 'Podemos conversar sobre capacidad, asignación por skills, alertas de carga y el plan que mejor acompañe a tu operación.',
      'contact.point1': 'Analizá la situación actual de tu equipo.',
      'contact.point2': 'Conocé las funcionalidades relevantes para tu agencia.',
      'contact.point3': 'Encontrá una forma simple de empezar.',
      'contact.name': 'Nombre',
      'contact.organization': 'Agencia u organización',
      'contact.email': 'Correo electrónico',
      'contact.message': '¿Qué necesitás resolver?',
      'contact.send': 'Enviar consulta',
      'contact.note': 'Usaremos estos datos únicamente para responder a tu consulta y dar seguimiento comercial.',

      'plans.eyebrow': 'Planes TeamBalance',
      'plans.title': 'Una versión para cada etapa de crecimiento.',
      'plans.subtitle': 'Elegí la capacidad adecuada para tu agencia. Todos los planes se contratan mensualmente e incluyen la puesta en marcha básica.',
      'plans.month': 'mes',
      'plans.hire': 'Contratar TeamBalance',
      'plans.compare': 'Comparar planes',
      'plans.hideComparison': 'Ocultar comparación',
      'plans.comparison.title': 'Compará capacidades y funcionalidades',
      'plans.comparison.subtitle': 'Revisá qué incorpora cada modalidad antes de contratar.',
      'plans.comparison.feature': 'Funcionalidad',
      'plans.comparison.select': 'Seleccionar para comparar', 'plans.comparison.selected': 'Planes seleccionados:', 'plans.comparison.selectionHelp': 'Elegí al menos 2 para comparar.', 'plans.comparison.minimum': 'Seleccioná al menos 2 planes para compararlos.', 'plans.comparison.maximum': 'Podés comparar como máximo 4 planes.',
      'plans.questions.open': 'Ver preguntas sobre', 'plans.questions.title': 'Preguntas sobre este plan', 'plans.questions.description': 'Dejá tu consulta y revisá las preguntas que hicieron otras personas.', 'plans.questions.name': 'Tu nombre', 'plans.questions.email': 'Tu email', 'plans.questions.question': 'Tu consulta', 'plans.questions.send': 'Enviar consulta', 'plans.questions.saving': 'Enviando…', 'plans.questions.previous': 'Consultas anteriores', 'plans.questions.empty': 'Todavía no hay consultas sobre este plan.', 'plans.questions.loadError': 'No pudimos cargar las consultas del plan.', 'plans.questions.saveError': 'No pudimos guardar tu consulta. Intentá nuevamente.', 'plans.questions.completeRequired': 'Completá correctamente nombre, email y consulta para enviarla.',
      'plans.loadError': 'No pudimos cargar los planes disponibles.',
      'plans.empty': 'No hay planes activos disponibles en este momento.',
      'plans.description.entry': 'Para agencias de hasta 20 usuarios.',
      'plans.description.business': 'Para agencias de 21 a 50 usuarios.',
      'plans.description.corporate': 'Para agencias de 51 a 200 usuarios.',
      'plans.onboarding.eyebrow': 'Incluido en la suscripción',
      'plans.onboarding.title': 'Te acompañamos en la puesta en marcha',
      'plans.onboarding.text': 'La contratación incluye el alta de la cuenta, configuración básica, carga inicial de datos y capacitación inicial para comenzar.',
      'plans.custom.title': '¿Necesitás algo adicional?',
      'plans.custom.text': 'Capacitaciones adicionales, integraciones y adaptaciones específicas se cotizan según el alcance.',
      'plans.custom.cta': 'Consultar servicio',
      'plans.feature.projects-resources': 'Gestión de proyectos y recursos',
      'plans.feature.best-fit': 'Motor Best Fit',
      'plans.feature.dashboards': 'Dashboards operativos',
      'plans.feature.alerts': 'Alertas',
      'plans.feature.standard-reports': 'Reportes estándar',
      'plans.feature.documentation': 'Documentación de uso',
      'plans.feature.standard-support': 'Soporte estándar',
      'plans.feature.updates': 'Actualizaciones del sistema',
      'plans.feature.onboarding': 'Puesta en marcha básica',
      'plans.feature.extended-reports': 'Reportes ampliados',
      'plans.feature.capacity-tracking': 'Seguimiento de capacidad',
      'plans.feature.priority-support': 'Soporte prioritario',
      'plans.feature.adoption-support': 'Acompañamiento inicial de adopción',
      'plans.feature.advanced-analytics': 'Analítica operativa avanzada',
      'plans.feature.reinforced-support': 'Soporte prioritario reforzado',
      'plans.feature.commercial-follow-up': 'Seguimiento comercial y operativo',

      'planManager.eyebrow': 'Administración comercial',
      'planManager.title': 'Gestión de planes',
      'planManager.subtitle': 'Creá, actualizá y administrá la vigencia de los planes que se muestran en la web pública.',
      'planManager.new': 'Nuevo plan',
      'planManager.list': 'Planes configurados',
      'planManager.name': 'Nombre',
      'planManager.description': 'Descripción',
      'planManager.price': 'Precio',
      'planManager.currency': 'Moneda',
      'planManager.periodicity': 'Periodicidad',
      'planManager.duration': 'Duración en meses',
      'planManager.features': 'Funcionalidades',
      'planManager.featuresHelp': 'Separá las funcionalidades con punto y coma (;).',
      'planManager.renewal': 'Condiciones de renovación',
      'planManager.start': 'Vigente desde',
      'planManager.end': 'Vigente hasta',
      'planManager.status': 'Estado',
      'planManager.saved': 'El plan se guardó correctamente.',
      'planManager.error': 'No pudimos completar la operación.',

      'checkout.eyebrow': 'Contratación TeamBalance',
      'checkout.title': 'Completá tu contratación.',
      'checkout.subtitle': 'Ingresá los datos de tu agencia y revisá el plan antes de continuar al pago.',
      'checkout.summary': 'Resumen de compra',
      'checkout.changePlan': 'Cambiar plan',
      'checkout.continue': 'Continuar al pago',
      'checkout.redirecting': 'Estamos redirigiéndote al sitio seguro de pago.',
      'checkout.noPlan': 'Seleccioná un plan antes de continuar.',

      'logs.title': 'Bitácora de actividad y accesos',
      'logs.filters': 'Filtros de búsqueda',
      'logs.date': 'Fecha',
      'logs.agency': 'Agencia',
      'logs.user': 'Usuario',
      'logs.module': 'Módulo',
      'logs.action': 'Acción',
      'logs.result': 'Resultado',
      'logs.criticality': 'Criticidad',
      'logs.subtitle': 'Consultá los eventos registrados y aplicá varios criterios de búsqueda.',
      'logs.from': 'Desde',
      'logs.to': 'Hasta',
      'logs.entity': 'Entidad',
      'logs.clear': 'Limpiar filtros',
      'logs.apply': 'Aplicar filtros',
      'logs.events': 'Eventos registrados',
      'logs.empty': 'No se encontraron eventos con los filtros aplicados.',
      'logs.details': 'Detalle del evento',
      'logs.message': 'Mensaje',
      'logs.error': 'No fue posible consultar la bitácora.',
      'dashboard.eyebrow': 'Panel operativo',
      'dashboard.greeting': 'Buen día',
      'dashboard.summary': 'Este es el resumen de las herramientas y operaciones disponibles para tu rol.',
      'dashboard.session': 'Sesión activa',
      'dashboard.accesses': 'Accesos habilitados',
      'dashboard.activeProjects': 'Proyectos activos',
      'dashboard.inProgress': 'En curso',
      'dashboard.sessionStatus': 'Estado de sesión',
      'dashboard.protected': 'Protegida',
      'dashboard.projects': 'Proyectos',
      'dashboard.manageProjects': 'Gestionar proyectos',
      'dashboard.projectsSubtitle': 'Seguimiento rápido de los proyectos activos de la agencia.',
      'dashboard.newProject': 'Nuevo proyecto',
      'dashboard.hide': 'Ocultar',
      'dashboard.viewProjects': 'Ver proyectos',
      'dashboard.loadingProjects': 'Cargando proyectos…',
      'dashboard.noDescription': 'Sin descripción registrada',
      'dashboard.view': 'Ver',
      'dashboard.emptyProjectsTitle': 'Todavía no hay proyectos activos',
      'dashboard.emptyProjectsText': 'Creá un proyecto para empezar a organizar tareas, responsables y plazos.',
      'dashboard.nextSteps': 'Próximos pasos',
      'dashboard.tools': 'Herramientas de trabajo',
      'dashboard.toolsSubtitle': 'Accesos disponibles según tus permisos.',
      'tasks.eyebrow': 'Planificación',
      'tasks.title': 'Gestión de tareas',
      'tasks.subtitle': 'Definí, ordená y asigná el trabajo de cada proyecto.',
      'tasks.new': 'Nueva tarea',
      'tasks.edit': 'Editar tarea',
      'tasks.newHelp': 'Definí el trabajo a realizar',
      'tasks.skill': 'Skill requerida',
      'tasks.selectSkill': 'Seleccioná una skill',
      'tasks.addSkill': 'Skill',
      'tasks.catalog': 'Catálogo',
      'tasks.skillDialog': 'Skills para tareas',
      'tasks.skillDialogText': 'Creá una skill para usarla inmediatamente en esta tarea.',
      'tasks.availableSkills': 'Skills disponibles',
      'tasks.save': 'Guardar tarea',
      'tasks.planned': 'Tareas planificadas',
      'tasks.emptyTitle': 'Sin tareas todavía',
      'tasks.emptyText': 'Primero registrá un proyecto, creá las skills necesarias y luego organizá sus tareas.',
      'myTasks.eyebrow': 'Mi operación',
      'myTasks.title': 'Mis tareas',
      'myTasks.subtitle': 'Consultá tus pendientes, prioridades y vencimientos en una vista personal.',
      'myTasks.logHours': 'Registrar horas',
      'myTasks.pending': 'Trabajo pendiente',
      'myTasks.pendingHelp': 'Las tareas asignadas a tu usuario aparecen en este panel.',
      'myTasks.loading': 'Cargando tus tareas…',
      'myTasks.emptyTitle': 'Todavía no hay tareas para mostrar',
      'myTasks.emptyText': 'Cuando te asignen una tarea, vas a poder revisar su estado, prioridad y vencimiento desde acá.',
      'myTasks.noDescription': 'Sin descripción',
      'myTasks.due': 'Vence:',
      'myTasks.noDue': 'Sin vencimiento',
      'myTasks.week': 'Mi semana',
      'myTasks.organize': 'Organizá tu trabajo',
      'myTasks.kanbanHelp': 'Usá el tablero Kanban para visualizar el estado de cada tarea asignada.',
      'myTasks.openKanban': 'Abrir tablero Kanban',
      'subscription.eyebrow': 'Suscripción',
      'subscription.title': 'Tu servicio TeamBalance',
      'subscription.subtitle': 'Consultá el estado de tu contratación y encontrá ayuda para administrar el servicio.',
      'subscription.current': 'Estado actual',
      'subscription.info': 'Información de suscripción',
      'subscription.loading': 'Cargando información de la suscripción…',
      'subscription.plan': 'Plan',
      'subscription.status': 'Estado',
      'subscription.amount': 'Importe vigente',
      'subscription.expiration': 'Vencimiento',
      'subscription.renewal': 'Renovación',
      'subscription.reference': 'Referencia',
      'subscription.automatic': 'Automática',
      'subscription.manual': 'Manual',
      'subscription.empty': 'Esta agencia todavía no tiene una suscripción registrada.',
      'subscription.help': '¿Necesitás ayuda?',
      'subscription.helpText': 'Nuestro equipo puede orientarte sobre tu contratación, facturación y adopción de TeamBalance.',
      'subscription.contact': 'Contactar soporte',
      'projects.eyebrow': 'Proyectos',
      'projects.title': 'Gestión de proyectos',
      'projects.subtitle': 'Organizá los proyectos, sus responsables y plazos.',
      'projects.new': 'Nuevo proyecto',
      'employees.eyebrow': 'Agencia',
      'employees.title': 'Gestión de empleados',
      'employees.subtitle': 'Administrá los usuarios, sus roles, skills y disponibilidad base.',
      'employees.new': 'Nuevo usuario',
      'employees.edit': 'Editar usuario',
      'roles.eyebrow': 'Soporte TeamBalance',
      'roles.title': 'Gestión de roles',
      'roles.subtitle': 'Los permisos son rutas estáticas de la plataforma. Los roles agrupan esos permisos y pueden asignarse a uno o varios usuarios.',
      'roles.new': 'Nuevo rol',
      'roles.edit': 'Editar rol',
      'roles.name': 'Nombre',
      'roles.description': 'Descripción',
      'roles.userType': 'Tipo de usuario',
      'roles.userTypeHelp': 'Clasifica el rol para que TeamBalance cree el perfil correspondiente al asignarlo.',
      'roles.permissions': 'Permisos estáticos',
      'roles.save': 'Guardar rol',
      'roles.list': 'Roles configurados',
      'roles.base': 'Rol base',
      'roles.assignedPermissions': 'permisos asignados',
      'roles.owner': 'Dueño',
      'roles.ownerHelp': 'Administración general de una agencia.',
      'roles.pm': 'Project Manager',
      'roles.pmHelp': 'Planificación y gestión operativa.',
      'roles.employee': 'Empleado',
      'roles.employeeHelp': 'Ejecución de tareas y registro operativo.',
      'roles.support': 'Soporte TeamBalance',
      'roles.supportHelp': 'Operación interna de TeamBalance.',
      'profile.eyebrow': 'Cuenta', 'profile.title': 'Mi perfil', 'profile.subtitle': 'Información de la cuenta con la que accedés a TeamBalance.', 'profile.email': 'Correo electrónico', 'profile.mainRole': 'Rol principal', 'profile.userType': 'Tipo de usuario', 'profile.agency': 'Agencia', 'profile.internalTeam': 'Equipo TeamBalance', 'profile.security': 'Seguridad de la cuenta', 'profile.securityText': 'Actualizá tu contraseña y cerrá las sesiones activas por seguridad.', 'profile.missing': 'No encontramos tu información de perfil', 'profile.missingText': 'Volvé a iniciar sesión para actualizar los datos de la cuenta.',
      'security.title': 'Seguridad de la cuenta', 'security.eyebrow': 'Mi cuenta', 'security.change': 'Cambiar contraseña', 'security.help': 'Al confirmar el cambio, se cerrarán las sesiones activas y tendrás que iniciar sesión nuevamente.', 'security.current': 'Contraseña actual', 'security.new': 'Nueva contraseña', 'security.repeat': 'Repetir nueva contraseña', 'security.updating': 'Actualizando…',
      'kanban.eyebrow': 'Mi operación', 'kanban.title': 'Tablero Kanban', 'kanban.subtitle': 'Visualizá el flujo de las tareas que te asignaron por estado.', 'kanban.loading': 'Cargando tablero…', 'kanban.empty': 'Sin tareas en este estado.', 'kanban.noDescription': 'Sin descripción', 'kanban.due': 'Vence:', 'kanban.noDue': 'Sin vencimiento',
      'common.name': 'Nombre', 'common.lastName': 'Apellido', 'common.email': 'Correo electrónico', 'common.phone': 'Teléfono', 'common.description': 'Descripción', 'common.status': 'Estado', 'common.start': 'Inicio', 'common.deadline': 'Fecha límite', 'common.hoursEstimated': 'Horas estimadas', 'common.noAdditionalData': 'Sin datos adicionales', 'common.noData': 'Sin datos', 'common.options': 'Opciones', 'common.reactivate': 'Reactivar', 'common.backToSignin': 'Ir a iniciar sesión',
      'profile.name': 'Nombre', 'profile.lastName': 'Apellido', 'profile.changePassword': 'Cambiar contraseña',
      'security.changed': 'La contraseña fue actualizada. Iniciá sesión nuevamente.', 'security.mismatch': 'La nueva contraseña debe tener al menos 8 caracteres y ambas contraseñas deben coincidir.', 'security.error': 'No fue posible modificar la contraseña. Intentá nuevamente.',
      'agency.eyebrow': 'Configuración', 'agency.title': 'Datos de la agencia', 'agency.subtitle': 'Mantené actualizada la información institucional que identifica a tu agencia en TeamBalance.', 'agency.commercialName': 'Nombre comercial', 'agency.businessName': 'Razón social', 'agency.taxId': 'CUIT', 'agency.taxCondition': 'Condición fiscal', 'agency.selectTaxCondition': 'Seleccionar condición', 'agency.billingEmail': 'Email de facturación', 'agency.contactPhone': 'Teléfono de contacto', 'agency.createdAt': 'Fecha de alta', 'agency.nonEditable': 'no editable', 'agency.saveChanges': 'Guardar cambios', 'agency.loading': 'Cargando datos de la agencia…', 'agency.organization': 'Organización', 'agency.asideTitle': 'Una base ordenada para operar', 'agency.asideText': 'Estos datos se usan como referencia institucional en las gestiones administrativas de TeamBalance.',
      'projects.edit': 'Editar proyecto', 'projects.close': 'Cerrar', 'projects.client': 'Cliente', 'projects.selectClient': 'Seleccioná un cliente', 'projects.newClient': 'Nuevo cliente', 'projects.editClient': 'Editar cliente', 'projects.pm': 'PM responsable', 'projects.selectManager': 'Seleccioná un responsable', 'projects.status': 'Estado', 'projects.planned': 'Planificado', 'projects.inProgress': 'En curso', 'projects.completed': 'Finalizado', 'projects.description': 'Descripción', 'projects.save': 'Guardar proyecto', 'projects.clients': 'Clientes de la agencia', 'projects.clientsText': 'Administrá los clientes sin salir de Proyectos.', 'projects.agencyProjects': 'Proyectos de la agencia', 'projects.emptyTitle': 'Sin proyectos todavía', 'projects.emptyText': 'Creá un cliente desde el formulario y empezá tu primer proyecto.', 'projects.deactivate': 'Dar de baja', 'projects.activate': 'Activar',
      'tasks.editing': 'Edición', 'tasks.newTask': 'Nueva tarea', 'tasks.close': 'Cerrar', 'tasks.titleLabel': 'Título', 'tasks.project': 'Proyecto', 'tasks.selectProject': 'Seleccioná un proyecto', 'tasks.status': 'Estado', 'tasks.selectStatus': 'Seleccioná un estado', 'tasks.assignedTo': 'Asignado', 'tasks.unassigned': 'Sin asignar', 'tasks.priority': 'Prioridad', 'tasks.complexity': 'Complejidad', 'tasks.progress': 'Avance', 'tasks.attachments': 'URLs de imágenes adjuntas (máximo 5)', 'tasks.attachmentsPlaceholder': 'Pegá una URL externa por línea. Por ejemplo, una imagen subida a Cloudinary.', 'tasks.attachmentsHelp': 'Las imágenes se guardan como URLs serializadas en JSON; TeamBalance no almacena archivos dentro de SQL.', 'tasks.cancel': 'Cancelar', 'tasks.catalogEyebrow': 'Catálogo', 'tasks.createSkill': 'Crear', 'tasks.skillCategory': 'Categoría', 'tasks.hours': 'h estimadas', 'tasks.noPriority': 'Sin prioridad', 'tasks.progressAria': 'Avance',
      'employees.supportNote': 'El rol Soporte se muestra sólo para crear el primer usuario interno de TeamBalance.', 'employees.workEmail': 'Email laboral', 'employees.temporaryPassword': 'Contraseña temporal', 'employees.temporaryPasswordEdit': 'Contraseña temporal (no cambia la actual)', 'employees.roles': 'Roles', 'employees.workProfile': 'Perfil laboral', 'employees.hourCost': 'Costo por hora', 'employees.weeklyHours': 'Horas semanales disponibles', 'employees.seniority': 'Seniority', 'employees.workStatus': 'Estado laboral', 'employees.startTime': 'Hora de inicio', 'employees.endTime': 'Hora de fin', 'employees.availabilityNote': 'Observación de disponibilidad', 'employees.skills': 'Skills del empleado', 'employees.register': 'Registrar usuario', 'employees.catalog': 'Catálogo de skills', 'employees.catalogText': 'Creá las skills que después asignás a empleados y tareas.', 'employees.createSkill': 'Crear skill', 'employees.agencyUsers': 'Usuarios de la agencia', 'employees.user': 'Usuario', 'employees.loadingUsers': 'Cargando usuarios…',
      'employees.simpleSearch': 'Búsqueda simple', 'employees.simpleSearchPlaceholder': 'Buscá por nombre o email', 'employees.advancedSearch': 'Búsqueda avanzada', 'employees.hideAdvancedSearch': 'Ocultar filtros avanzados', 'employees.searchHelp': 'Encontrá usuarios rápidamente o combiná varios criterios.', 'employees.all': 'Todos', 'employees.noResults': 'No encontramos usuarios con esos filtros.',
      'hours.eyebrow': 'Mi operación', 'hours.title': 'Registrar horas', 'hours.subtitle': 'Informá el tiempo dedicado a una tarea para mantener actualizada la carga operativa.', 'hours.task': 'Tarea', 'hours.taskPlaceholder': 'Seleccioná o ingresá una tarea', 'hours.date': 'Fecha', 'hours.hours': 'Horas', 'hours.optionalDescription': 'Descripción opcional', 'hours.descriptionPlaceholder': 'Ej.: revisión de entregable', 'hours.save': 'Guardar registro', 'hours.success': 'El registro quedó listo para integrarse con la gestión de tareas.',
      'availability.eyebrow': 'Mi operación', 'availability.title': 'Mi disponibilidad', 'availability.subtitle': 'Mantené visible tu capacidad para mejorar la planificación del equipo.', 'availability.schedule': 'Horario y ausencias', 'availability.help': 'Definí tu disponibilidad semanal cuando la configuración esté habilitada.', 'availability.licenses': 'Licencias y ausencias', 'availability.update': 'Actualizar disponibilidad', 'availability.emptyTitle': 'Todavía no hay disponibilidad registrada', 'availability.emptyText': 'Los horarios, ausencias y licencias que cargues aparecerán en esta sección y se usarán para planificar tareas.',
    },

    en: {
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.search': 'Search',
      'common.close': 'Close',
      'common.edit': 'Edit',
      'common.create': 'Create',
      'common.update': 'Update',
      'common.active': 'Active',
      'common.inactive': 'Inactive',
      'common.activate': 'Activate',
      'common.deactivate': 'Deactivate',
      'common.loading': 'Loading…',
      'common.retry': 'Try again',
      'common.included': 'Included',
      'common.required': 'Complete this field.',

      'faq.kicker': 'Help center', 'faq.title': 'Frequently asked questions', 'faq.description': 'Find quick answers about using TeamBalance every day. This guide is updated along with the platform features.', 'faq.searchLabel': 'Search for an answer', 'faq.searchPlaceholder': 'E.g. log hours, availability or subscription', 'faq.answerFound': 'answer found', 'faq.answersFound': 'answers found', 'faq.filterLabel': 'Filter questions by category', 'faq.listLabel': 'Frequently asked questions list', 'faq.emptyTitle': 'We could not find an answer for that search.', 'faq.emptyText': 'Try another word or contact the person responsible for your agency.', 'faq.needHelpKicker': 'Still need help?', 'faq.needHelpTitle': 'Open a support request', 'faq.needHelpDescription': 'HelpDesk lets you submit a request and continue the conversation when Support replies. Do not share passwords, verification codes or card details.', 'faq.openSupport': 'Open HelpDesk', 'faq.configureNewsletter': 'Configure newsletter', 'faq.category.all': 'All', 'faq.category.firstSteps': 'Getting started', 'faq.category.projects': 'Projects and tasks', 'faq.category.team': 'Team and availability', 'faq.category.account': 'Account and subscription', 'faq.access.question': 'How do I know which options I can use?', 'faq.access.answer': 'The available options depend on your role and permissions. If you need a missing feature, contact the person responsible for your agency.', 'faq.project.question': 'How do I create and plan a task?', 'faq.project.answer': 'From Projects, the PM enters task data and can assign a person or request a Best Fit suggestion.', 'faq.kanban.question': 'How do I update a task status or progress?', 'faq.kanban.answer': 'Open the task from the Kanban board. In its detail you can change status, mark subtasks and add comments.', 'faq.hours.question': 'Why can’t I log hours for a date?', 'faq.hours.answer': 'The record must respect the allowed date range, does not accept future dates and only allows tasks available to you.', 'faq.bestFit.question': 'What does Best Fit analyze?', 'faq.bestFit.answer': 'Best Fit compares required skills, seniority, availability and workload. It is a recommendation: it does not automatically assign or move anyone.', 'faq.availability.question': 'How do I report an absence or availability change?', 'faq.availability.answer': 'From My availability you can maintain your base schedule and register leaves or absences when needed.', 'faq.skills.question': 'What are skills and seniority for?', 'faq.skills.answer': 'Skills describe concrete capabilities and seniority indicates the recommended level for a task.', 'faq.subscription.question': 'How do I manage my agency subscription?', 'faq.subscription.answer': 'The Owner can check the current plan, history and renewal under Agency settings > Subscription.', 'faq.security.question': 'How do I protect my account?', 'faq.security.answer': 'Do not share credentials or verification codes. Use a strong password and report unexpected access.',
      'helpdesk.kicker': 'Help center', 'helpdesk.title': 'Asynchronous support', 'helpdesk.description': 'Submit a request and follow the Support team response.', 'helpdesk.backoffice': 'TeamBalance Support', 'helpdesk.inboxTitle': 'Support inbox', 'helpdesk.inboxDescription': 'Review user requests, reply to them and keep their status updated.', 'helpdesk.newTicket': 'New request', 'helpdesk.question': 'How can we help you?', 'helpdesk.category': 'Category', 'helpdesk.subject': 'Subject', 'helpdesk.subjectPlaceholder': 'E.g. I cannot access the board', 'helpdesk.descriptionLabel': 'Description', 'helpdesk.descriptionPlaceholder': 'Tell us what you were doing and what you need to solve.', 'helpdesk.sensitiveWarning': 'Do not include passwords, verification codes or card details.', 'helpdesk.creating': 'Creating…', 'helpdesk.create': 'Create request', 'helpdesk.followUp': 'Follow-up', 'helpdesk.myTickets': 'My requests', 'helpdesk.inbox': 'Inbox', 'helpdesk.customerTickets': 'User requests', 'helpdesk.noAgency': 'No agency', 'helpdesk.messages': 'message(s)', 'helpdesk.myTicketsEmpty': 'You have not submitted support requests yet.', 'helpdesk.inboxEmpty': 'There are no requests awaiting attention.', 'helpdesk.status': 'Status', 'helpdesk.service': 'TeamBalance service', 'helpdesk.resolve': 'Mark as resolved', 'helpdesk.changeStatus': 'Update status', 'helpdesk.saveStatus': 'Save status', 'helpdesk.you': 'You', 'helpdesk.team': 'TeamBalance Support', 'helpdesk.reply': 'Reply to user', 'helpdesk.addInfo': 'Add information', 'helpdesk.sending': 'Sending…', 'helpdesk.send': 'Send message', 'helpdesk.selectTicket': 'Select a request to view the conversation and follow-up.', 'helpdesk.created': 'Request created successfully. Support will respond asynchronously.', 'helpdesk.loadError': 'We could not load the requests.', 'helpdesk.createError': 'The request could not be created.', 'helpdesk.detailError': 'We could not open the request.', 'helpdesk.sendError': 'The message could not be sent.', 'helpdesk.statusSaved': 'Status updated successfully.', 'helpdesk.statusError': 'The status could not be updated.', 'helpdesk.resolved': 'Request marked as resolved.', 'helpdesk.category.Acceso': 'Access', 'helpdesk.category.Usuarios': 'Users', 'helpdesk.category.Funcionalidad': 'Feature', 'helpdesk.category.Suscripción y pagos': 'Subscription and payments', 'helpdesk.category.Otro': 'Other', 'helpdesk.status.Pendiente': 'Pending', 'helpdesk.status.En revisión': 'Under review', 'helpdesk.status.Respondida': 'Answered', 'helpdesk.status.Resuelta': 'Resolved',
      'news.kicker': 'Communications', 'news.preferencesTitle': 'Email updates', 'news.preferencesDescription': 'Choose the communications you want to receive and change them whenever you want.', 'news.backoffice': 'Communications', 'news.managementTitle': 'News management', 'news.managementDescription': 'Publish communications and manage their validity without receiving newsletters.', 'news.newsletterKicker': 'Newsletter', 'news.myCategories': 'My categories', 'news.preferencesHint': 'Public news remains available on the website; these preferences only determine which categories reach your email.', 'news.savePreferences': 'Save preferences', 'news.publishKicker': 'Support backoffice', 'news.publishTitle': 'Publish news', 'news.category': 'Category', 'news.selectCategory': 'Select category', 'news.newsTitle': 'Title', 'news.content': 'Content', 'news.imageUrl': 'Image URL (optional)', 'news.publicationDate': 'Publication', 'news.expirationDate': 'Expiration', 'news.publishHint': 'If you do not specify a publication date, it is published now. Once it expires, it is removed from the public page.', 'news.publishing': 'Publishing…', 'news.publishAndSend': 'Publish and send newsletter', 'news.historyKicker': 'History', 'news.historyTitle': 'Managed news', 'news.publishedAt': 'Publication', 'news.sent': 'Newsletter processed', 'news.pending': 'Pending delivery', 'news.historyEmpty': 'There is no published news yet.', 'news.loadError': 'We could not load the news.', 'news.preferencesSaved': 'Newsletter preferences saved successfully.', 'news.preferencesError': 'Newsletter preferences could not be saved.', 'news.published': 'News published. It will be emailed to users subscribed to the category.', 'news.publishError': 'The news could not be published.', 'news.deactivated': 'News deactivated successfully.', 'news.deactivateError': 'The news could not be deactivated.',

      'signin': 'Sign in',
      'view-plans': 'View plans',
      'login.title': 'Sign in',
      'login.email': 'Email',
      'login.password': 'Password',
      'login.remember': 'Keep me signed in',
      'login.button': 'Sign in',
      'login.forgotPassword': 'Forgot your password?',
      'login.back': 'Back to home',
      'login.eyebrow': 'Platform access',
      'login.welcome': 'Welcome back.',
      'login.subtitle': 'Sign in with your credentials to continue managing your team.',
      'login.workEmail': 'Work email',
      'login.showPassword': 'Show password',
      'login.hidePassword': 'Hide password',
      'login.submitting': 'Signing in…',
      'login.start': 'Want to start using TeamBalance?',
      'login.choosePlan': 'Choose your plan',
      'login.resend': 'Did not receive the validation email?',
      'login.resendLink': 'Resend link',
      'login.invalid': 'Enter a valid email and your password.',
      'signup.eyebrow': 'Agency registration',
      'signup.verifying': 'Verifying your subscription.',
      'signup.verifyingText': 'We are checking that payment has been approved before enabling the initial access.',
      'signup.cannotContinue': 'We cannot continue',
      'signup.needsApproved': 'Registration requires an approved subscription.',
      'signup.choosePlan': 'Choose a plan',
      'signup.started': 'Registration started',
      'signup.completed': 'Your agency was registered.',
      'signup.emailSent': 'Initial access is associated with the Owner role. We sent you a link to confirm your email before signing in.',
      'signup.emailNotSent': 'Initial access is associated with the Owner role, but we could not send the validation email. You can request a new link from the sign-in page.',
      'signup.goSignin': 'Go to sign in',
      'signup.resend': 'Resend validation',
      'signup.backPlans': 'Back to plans',
      'signup.title': 'Complete your access details.',
      'signup.subtitle': 'Your subscription was approved. We will create the initial TeamBalance access with the Owner role.',
      'signup.firstName': 'First name',
      'signup.lastName': 'Last name',
      'signup.yourName': 'Your first name',
      'signup.yourLastName': 'Your last name',
      'signup.minName': 'Enter at least 2 characters.',
      'signup.workEmail': 'Work email',
      'signup.invalidEmail': 'Enter a valid work email.',
      'signup.phone': 'Contact phone',
      'signup.invalidPhone': 'Enter a valid contact phone number.',
      'signup.password': 'Password',
      'signup.createPassword': 'Create a password',
      'signup.passwordHint': 'Use at least 8 characters, combining letters and numbers.',
      'signup.passwordError': 'The password must meet the listed requirements.',
      'signup.confirmPassword': 'Confirm password',
      'signup.repeatPassword': 'Repeat your password',
      'signup.confirmError': 'Confirm the password you selected.',
      'signup.termsPrefix': 'I have read and accept TeamBalance', 'signup.termsLink': 'Terms and Conditions', 'signup.termsSuffix': '.', 'signup.termsError': 'You must accept the Terms and Conditions to complete registration.',
      'signup.newsletterOptIn': 'I want to receive TeamBalance updates by email.',
      'signup.newsletterCategoriesHint': 'Choose the categories that interest you. You can change them whenever you want.',
      'signup.newsletterCategoryRequired': 'Choose at least one category or unsubscribe from email updates.',
      'signup.creating': 'Creating access…',
      'signup.create': 'Create initial access',
      'signup.haveAccount': 'Already have an account?',
      'auth.asideLabel': 'About TeamBalance',
      'auth.smartTeamManagement': 'Smart team management',
      'auth.agencyOperationsContext': 'Your agency’s operations, with more context.',
      'auth.teamManagementDescription': 'Bring people, projects and capacity together in one view to make better decisions every day.',
      'auth.teamOverview': 'Team overview',
      'auth.availableCapacity': 'Available capacity',
      'auth.thisWeekIncrease': '+12% this week',
      'auth.activeAlerts': 'Active alerts',
      'auth.reviewToday': 'To review today',
      'auth.product': 'Product',
      'auth.development': 'Development',
      'auth.design': 'Design',
      'auth.availabilityWorkloadVisible': 'Visibility into availability and workload',
      'auth.skillsSeniorityAssignment': 'Skills and seniority for better assignments',
      'auth.anticipateIssues': 'Alerts to anticipate potential issues',

      'menu.home': 'Home',
      'menu.dashboard': 'Dashboard',
      'menu.projects': 'Projects',
      'menu.employees': 'Employees',
      'menu.security': 'Security',
      'menu.logout': 'Sign out',
      'menu.plans': 'Plans',
      'menu.about': 'About us',
      'menu.contact': 'Contact',
      'menu.calendar': 'Calendar',
      'menu.logs': 'Activity log',
      'menu.help': 'Help',
      'menu.support': 'Support',
      'menu.newsletter': 'Email updates',
      'menu.supportInbox': 'Support inbox',
      'menu.newsManagement': 'News management',
      'menu.operators': 'Operators',
      'menu.backups': 'Backups',
      'menu.profile': 'Profile',
      'menu.tasks': 'Tasks',
      'menu.reports': 'Reports',
      'menu.agency': 'Agency settings',
      'menu.subscription': 'Subscription',
      'menu.bestFit': 'Best Fit',
      'menu.teamCalendar': 'Team calendar',
      'menu.simulation': 'Impact simulation',
      'menu.skillsCoverage': 'Skills coverage',
      'menu.templates': 'Task templates',
      'menu.myTasks': 'My tasks',
      'menu.kanban': 'Kanban board',
      'menu.registerHours': 'Log hours',
      'menu.availability': 'My availability',
      'menu.workload': 'My workload',
      'menu.roles': 'Roles',
      'menu.plansManagement': 'Plan management',
      'operators.kicker': 'TeamBalance Back Office',
      'operators.title': 'Operator management',
      'operators.description': 'Create, update, activate or deactivate internal Support users. They do not belong to an agency and can only receive internal roles.',
      'operators.new': 'New operator',
      'operators.newTitle': 'New operator',
      'operators.editTitle': 'Edit operator',
      'operators.firstName': 'First name',
      'operators.lastName': 'Last name',
      'operators.email': 'Work email',
      'operators.password': 'Temporary password',
      'operators.passwordOptional': 'Temporary password (optional)',
      'operators.passwordHint': 'The person will need to verify their email before signing in.',
      'operators.passwordEditHint': 'Leave blank to keep the current password.',
      'operators.roles': 'Internal roles',
      'operators.roleRequired': 'Select at least one internal Support role.',
      'operators.required': 'Complete the required fields.',
      'operators.create': 'Create operator',
      'operators.list': 'Registered operators',
      'operators.listHelp': 'Status changes do not delete records or affect agency users.',
      'operators.empty': 'There are no internal operators registered yet.',
      'operators.created': 'Operator created successfully. A verification email was sent.',
      'operators.updated': 'Operator updated successfully.',
      'operators.activated': 'Operator activated successfully.',
      'operators.deactivated': 'Operator deactivated successfully.',
      'operators.loadError': 'We could not load internal operators.',
      'operators.saveError': 'We could not save the operator.',
      'operators.statusError': 'We could not update the operator status.',
      'backup.kicker': 'Operational continuity',
      'backup.title': 'Backup and restore',
      'backup.description': 'Manage full database copies. Backups are verified before becoming available and restore tests run in an isolated database.',
      'backup.rpo': 'Recovery point objective',
      'backup.rpoHelp': 'Maximum acceptable information loss.',
      'backup.rto': 'Recovery time objective',
      'backup.rtoHelp': 'Maximum expected time to recover the service.',
      'backup.retention': 'Retention',
      'backup.retentionHelp': 'Expired copies are purged in a controlled way.',
      'backup.days': 'days',
      'backup.createTitle': 'Create full backup',
      'backup.createHelp': 'Creates a SQL Server copy with checksum, runs RESTORE VERIFYONLY and retains a copy of the declared configuration files.',
      'backup.create': 'Create backup now',
      'backup.running': 'Processing…',
      'backup.created': 'The backup was generated and verified successfully.',
      'backup.createError': 'We could not create the backup. Check SQL Server permissions on the configured folder.',
      'backup.loadError': 'We could not load the backup history.',
      'backup.historyTitle': 'Backup history',
      'backup.historyHelp': 'Only full verified copies can be used for a restore test.',
      'backup.empty': 'No backups have been registered yet.',
      'backup.sizeUnavailable': 'Size unavailable',
      'backup.testRestore': 'Test restore',
      'backup.restoreKicker': 'Isolated environment',
      'backup.restoreTitle': 'Test a restore without impacting TeamBalance',
      'backup.restoreHelp': 'A temporary copy is restored into a separate database, integrity is checked, the outcome is logged and the database is then deleted. It never changes the production database.',
      'backup.restore': 'Restore in isolation',
      'backup.restoreComplete': 'The isolated restore test finished successfully.',
      'backup.restoreError': 'We could not complete the isolated restore test.',
      'backup.productionRestoreKicker': 'Contingency recovery',
      'backup.productionRestoreTitle': 'Restore the production database',
      'backup.productionRestoreHelp': 'This action replaces TeamBalance with the selected copy. Users will be disconnected and changes made after the backup date will be lost. Use it only during a real incident.',
      'backup.productionRestore': 'Recover production',
      'backup.productionRestoreError': 'We could not recover the production database. The application attempted to reopen the database to keep access available.',
      'backup.xmlKicker': 'External audit',
      'backup.xmlTitle': 'Continuity history',
      'backup.xmlHelp': 'External XML record independent from TeamBalance. It preserves backup and restore events even when the production database is recovered.',
      'backup.xmlEmpty': 'There are no events in the external XML history yet.',
      'backup.xmlType.Backup': 'Database backup',
      'backup.xmlType.RestoreAislado': 'Isolated restore test',
      'backup.xmlType.RestoreProduccion': 'Production recovery',
      'menu.product': 'Product',
      'menu.company': 'Company',
      'menu.legal': 'Legal',
      'menu.terms': 'Terms and conditions',
      'menu.privacy': 'Privacy policy',
      'menu.securityPolicy': 'Security policy',

      'footer.description': 'Capacity planning for project-based agencies and consulting firms.',
      'footer.rights': '© 2026 TeamBalance. All rights reserved.',
      'footer.tagline': 'Intelligent team management.',
      'about.eyebrow': 'About TeamBalance',
      'about.title': 'Better organized teams. Better informed decisions.',
      'about.lead': 'TeamBalance helps digital agencies and consulting firms organize people, projects and hours without relying on isolated spreadsheets.',
      'about.problem.eyebrow': 'The problem we solve',
      'about.problem.title': 'Profitability also needs planning.',
      'about.problem.text1': 'A wrong assignment affects deadlines, costs and well-being. Without visibility into capacity, critical profiles are overloaded and other resources are underused.',
      'about.problem.text2': 'TeamBalance brings this information together so owners and project managers can anticipate risks and compare alternatives.',
      'about.mission': 'Mission',
      'about.mission.title': 'Provide clarity for better assignment.',
      'about.mission.text': 'We simplify resource planning so every project has the right availability and profile.',
      'about.vision': 'Vision',
      'about.vision.title': 'More sustainable teams.',
      'about.vision.text': 'We aim to turn operational information into simple, useful and responsible decisions.',
      'about.focus': 'Approach',
      'about.focus.title': 'Data that explains a decision.',
      'about.focus.text': 'Skills, seniority, workload, availability and deadlines provide context without replacing human judgment.',
      'about.cta': 'Does your agency grow through projects?',
      'about.ctaTitle': 'Let us discuss planning with more context.',
      'about.ctaButton': 'Contact us',
      'contact.eyebrow': 'Contact',
      'contact.title': 'Let us talk about your team capacity.',
      'contact.lead': 'Tell us how your projects are organized today and where TeamBalance can add the most value.',
      'contact.asideEyebrow': 'A useful conversation',
      'contact.asideTitle': 'For agencies that want to decide with greater clarity.',
      'contact.asideText': 'We can discuss capacity planning, skill-based assignments, workload alerts and the plan that best supports your operation.',
      'contact.point1': 'Assess your team’s current situation.',
      'contact.point2': 'Learn about the relevant features for your agency.',
      'contact.point3': 'Find a simple way to get started.',
      'contact.name': 'Name',
      'contact.organization': 'Agency or organization',
      'contact.email': 'Email',
      'contact.message': 'What do you need to solve?',
      'contact.send': 'Send inquiry',
      'contact.note': 'We will use this information only to reply to your inquiry and provide commercial follow-up.',

      'plans.eyebrow': 'TeamBalance plans',
      'plans.title': 'One version for every stage of growth.',
      'plans.subtitle': 'Choose the right capacity for your agency. All plans are billed monthly and include basic onboarding.',
      'plans.month': 'month',
      'plans.hire': 'Get TeamBalance',
      'plans.compare': 'Compare plans',
      'plans.hideComparison': 'Hide comparison',
      'plans.comparison.title': 'Compare capacity and features',
      'plans.comparison.subtitle': 'Review what each option includes before purchasing.',
      'plans.comparison.feature': 'Feature',
      'plans.comparison.select': 'Select to compare', 'plans.comparison.selected': 'Selected plans:', 'plans.comparison.selectionHelp': 'Choose at least 2 to compare.', 'plans.comparison.minimum': 'Select at least 2 plans to compare.', 'plans.comparison.maximum': 'You can compare a maximum of 4 plans.',
      'plans.questions.open': 'View questions about', 'plans.questions.title': 'Questions about this plan', 'plans.questions.description': 'Leave your question and review questions from other people.', 'plans.questions.name': 'Your name', 'plans.questions.email': 'Your email', 'plans.questions.question': 'Your question', 'plans.questions.send': 'Send question', 'plans.questions.saving': 'Sending…', 'plans.questions.previous': 'Previous questions', 'plans.questions.empty': 'There are no questions about this plan yet.', 'plans.questions.loadError': 'We could not load this plan’s questions.', 'plans.questions.saveError': 'We could not save your question. Please try again.', 'plans.questions.completeRequired': 'Complete your name, email and question correctly before sending it.',
      'plans.loadError': 'We could not load the available plans.',
      'plans.empty': 'There are no active plans available right now.',
      'plans.description.entry': 'For agencies with up to 20 users.',
      'plans.description.business': 'For agencies with 21 to 50 users.',
      'plans.description.corporate': 'For agencies with 51 to 200 users.',
      'plans.onboarding.eyebrow': 'Included with your subscription',
      'plans.onboarding.title': 'We support your onboarding',
      'plans.onboarding.text': 'Your subscription includes account setup, basic configuration, initial data loading and initial training.',
      'plans.custom.title': 'Need something else?',
      'plans.custom.text': 'Additional training, integrations and specific adaptations are quoted according to scope.',
      'plans.custom.cta': 'Contact us',
      'plans.feature.projects-resources': 'Project and resource management',
      'plans.feature.best-fit': 'Best Fit engine',
      'plans.feature.dashboards': 'Operational dashboards',
      'plans.feature.alerts': 'Alerts',
      'plans.feature.standard-reports': 'Standard reports',
      'plans.feature.documentation': 'User documentation',
      'plans.feature.standard-support': 'Standard support',
      'plans.feature.updates': 'System updates',
      'plans.feature.onboarding': 'Basic onboarding',
      'plans.feature.extended-reports': 'Extended reports',
      'plans.feature.capacity-tracking': 'Capacity tracking',
      'plans.feature.priority-support': 'Priority support',
      'plans.feature.adoption-support': 'Initial adoption support',
      'plans.feature.advanced-analytics': 'Advanced operational analytics',
      'plans.feature.reinforced-support': 'Enhanced priority support',
      'plans.feature.commercial-follow-up': 'Commercial and operational follow-up',

      'planManager.eyebrow': 'Commercial administration',
      'planManager.title': 'Plan management',
      'planManager.subtitle': 'Create, update and manage the availability of plans shown on the public website.',
      'planManager.new': 'New plan',
      'planManager.list': 'Configured plans',
      'planManager.name': 'Name',
      'planManager.description': 'Description',
      'planManager.price': 'Price',
      'planManager.currency': 'Currency',
      'planManager.periodicity': 'Billing period',
      'planManager.duration': 'Duration in months',
      'planManager.features': 'Features',
      'planManager.featuresHelp': 'Separate features with a semicolon (;).',
      'planManager.renewal': 'Renewal conditions',
      'planManager.start': 'Available from',
      'planManager.end': 'Available until',
      'planManager.status': 'Status',
      'planManager.saved': 'The plan was saved successfully.',
      'planManager.error': 'We could not complete the operation.',

      'checkout.eyebrow': 'TeamBalance subscription',
      'checkout.title': 'Complete your subscription.',
      'checkout.subtitle': 'Enter your agency details and review the plan before continuing to payment.',
      'checkout.summary': 'Order summary',
      'checkout.changePlan': 'Change plan',
      'checkout.continue': 'Continue to payment',
      'checkout.redirecting': 'We are redirecting you to the secure payment site.',
      'checkout.noPlan': 'Select a plan before continuing.',

      'logs.title': 'Activity and access log',
      'logs.filters': 'Search filters',
      'logs.date': 'Date',
      'logs.agency': 'Agency',
      'logs.user': 'User',
      'logs.module': 'Module',
      'logs.action': 'Action',
      'logs.result': 'Result',
      'logs.criticality': 'Criticality',
      'logs.subtitle': 'Review recorded events and combine multiple search criteria.',
      'logs.from': 'From',
      'logs.to': 'To',
      'logs.entity': 'Entity',
      'logs.clear': 'Clear filters',
      'logs.apply': 'Apply filters',
      'logs.events': 'Recorded events',
      'logs.empty': 'No events matched the selected filters.',
      'logs.details': 'Event details',
      'logs.message': 'Message',
      'logs.error': 'The activity log could not be loaded.',
      'dashboard.eyebrow': 'Operations dashboard',
      'dashboard.greeting': 'Good morning',
      'dashboard.summary': 'This is a summary of the tools and operations available for your role.',
      'dashboard.session': 'Active session',
      'dashboard.accesses': 'Enabled access',
      'dashboard.activeProjects': 'Active projects',
      'dashboard.inProgress': 'In progress',
      'dashboard.sessionStatus': 'Session status',
      'dashboard.protected': 'Protected',
      'dashboard.projects': 'Projects',
      'dashboard.manageProjects': 'Manage projects',
      'dashboard.projectsSubtitle': 'Quick monitoring of the agency’s active projects.',
      'dashboard.newProject': 'New project',
      'dashboard.hide': 'Hide',
      'dashboard.viewProjects': 'View projects',
      'dashboard.loadingProjects': 'Loading projects…',
      'dashboard.noDescription': 'No description recorded',
      'dashboard.view': 'View',
      'dashboard.emptyProjectsTitle': 'There are no active projects yet',
      'dashboard.emptyProjectsText': 'Create a project to start organizing tasks, owners and deadlines.',
      'dashboard.nextSteps': 'Next steps',
      'dashboard.tools': 'Work tools',
      'dashboard.toolsSubtitle': 'Available access according to your permissions.',
      'tasks.eyebrow': 'Planning',
      'tasks.title': 'Task management',
      'tasks.subtitle': 'Define, prioritize and assign each project’s work.',
      'tasks.new': 'New task',
      'tasks.edit': 'Edit task',
      'tasks.newHelp': 'Define the work to be done',
      'tasks.skill': 'Required skill',
      'tasks.selectSkill': 'Select a skill',
      'tasks.addSkill': 'Skill',
      'tasks.catalog': 'Catalog',
      'tasks.skillDialog': 'Task skills',
      'tasks.skillDialogText': 'Create a skill to use it immediately in this task.',
      'tasks.availableSkills': 'Available skills',
      'tasks.save': 'Save task',
      'tasks.planned': 'Planned tasks',
      'tasks.emptyTitle': 'There are no tasks yet',
      'tasks.emptyText': 'First register a project, create the needed skills and then organize its tasks.',
      'myTasks.eyebrow': 'My operation',
      'myTasks.title': 'My tasks',
      'myTasks.subtitle': 'Review your pending work, priorities and due dates in one personal view.',
      'myTasks.logHours': 'Log hours',
      'myTasks.pending': 'Pending work',
      'myTasks.pendingHelp': 'Tasks assigned to your user appear in this panel.',
      'myTasks.loading': 'Loading your tasks…',
      'myTasks.emptyTitle': 'There are no tasks to show yet',
      'myTasks.emptyText': 'When a task is assigned to you, you will be able to review its status, priority and due date here.',
      'myTasks.noDescription': 'No description',
      'myTasks.due': 'Due:',
      'myTasks.noDue': 'No due date',
      'myTasks.week': 'My week',
      'myTasks.organize': 'Organize your work',
      'myTasks.kanbanHelp': 'Use the Kanban board to visualize the status of every task assigned to you.',
      'myTasks.openKanban': 'Open Kanban board',
      'subscription.eyebrow': 'Subscription',
      'subscription.title': 'Your TeamBalance service',
      'subscription.subtitle': 'Review your subscription status and find help managing the service.',
      'subscription.current': 'Current status',
      'subscription.info': 'Subscription information',
      'subscription.loading': 'Loading subscription information…',
      'subscription.plan': 'Plan',
      'subscription.status': 'Status',
      'subscription.amount': 'Current amount',
      'subscription.expiration': 'Expiration',
      'subscription.renewal': 'Renewal',
      'subscription.reference': 'Reference',
      'subscription.automatic': 'Automatic',
      'subscription.manual': 'Manual',
      'subscription.empty': 'This agency does not have a subscription registered yet.',
      'subscription.help': 'Need help?',
      'subscription.helpText': 'Our team can guide you through your subscription, billing and TeamBalance adoption.',
      'subscription.contact': 'Contact support',
      'projects.eyebrow': 'Projects',
      'projects.title': 'Project management',
      'projects.subtitle': 'Organize projects, their owners and deadlines.',
      'projects.new': 'New project',
      'employees.eyebrow': 'Agency',
      'employees.title': 'Employee management',
      'employees.subtitle': 'Manage users, their roles, skills and base availability.',
      'employees.new': 'New user',
      'employees.edit': 'Edit user',
      'roles.eyebrow': 'TeamBalance support',
      'roles.title': 'Role management',
      'roles.subtitle': 'Permissions are static platform routes. Roles group those permissions and can be assigned to one or more users.',
      'roles.new': 'New role',
      'roles.edit': 'Edit role',
      'roles.name': 'Name',
      'roles.description': 'Description',
      'roles.userType': 'User type',
      'roles.userTypeHelp': 'Classify the role so TeamBalance creates the corresponding profile when assigning it.',
      'roles.permissions': 'Static permissions',
      'roles.save': 'Save role',
      'roles.list': 'Configured roles',
      'roles.base': 'Base role',
      'roles.assignedPermissions': 'assigned permissions',
      'roles.owner': 'Owner',
      'roles.ownerHelp': 'General administration of an agency.',
      'roles.pm': 'Project Manager',
      'roles.pmHelp': 'Planning and operational management.',
      'roles.employee': 'Employee',
      'roles.employeeHelp': 'Task execution and operational records.',
      'roles.support': 'TeamBalance support',
      'roles.supportHelp': 'Internal TeamBalance operations.',
      'profile.eyebrow': 'Account', 'profile.title': 'My profile', 'profile.subtitle': 'Account information used to access TeamBalance.', 'profile.email': 'Email', 'profile.mainRole': 'Primary role', 'profile.userType': 'User type', 'profile.agency': 'Agency', 'profile.internalTeam': 'TeamBalance team', 'profile.security': 'Account security', 'profile.securityText': 'Update your password and close active sessions for security.', 'profile.missing': 'We could not find your profile information', 'profile.missingText': 'Sign in again to refresh your account information.',
      'security.title': 'Account security', 'security.eyebrow': 'My account', 'security.change': 'Change password', 'security.help': 'When you confirm the change, active sessions will be closed and you will need to sign in again.', 'security.current': 'Current password', 'security.new': 'New password', 'security.repeat': 'Repeat new password', 'security.updating': 'Updating…',
      'kanban.eyebrow': 'My operation', 'kanban.title': 'Kanban board', 'kanban.subtitle': 'Visualize the flow of tasks assigned to you by status.', 'kanban.loading': 'Loading board…', 'kanban.empty': 'No tasks in this status.', 'kanban.noDescription': 'No description', 'kanban.due': 'Due:', 'kanban.noDue': 'No due date',
      'common.name': 'Name', 'common.lastName': 'Last name', 'common.email': 'Email', 'common.phone': 'Phone', 'common.description': 'Description', 'common.status': 'Status', 'common.start': 'Start', 'common.deadline': 'Deadline', 'common.hoursEstimated': 'Estimated hours', 'common.noAdditionalData': 'No additional information', 'common.noData': 'No data', 'common.options': 'Options', 'common.reactivate': 'Reactivate', 'common.backToSignin': 'Go to sign in',
      'profile.name': 'Name', 'profile.lastName': 'Last name', 'profile.changePassword': 'Change password',
      'security.changed': 'Your password was updated. Sign in again.', 'security.mismatch': 'The new password must have at least 8 characters and both passwords must match.', 'security.error': 'Your password could not be changed. Please try again.',
      'agency.eyebrow': 'Settings', 'agency.title': 'Agency information', 'agency.subtitle': 'Keep the institutional information that identifies your agency in TeamBalance up to date.', 'agency.commercialName': 'Trade name', 'agency.businessName': 'Business name', 'agency.taxId': 'Tax ID', 'agency.taxCondition': 'Tax status', 'agency.selectTaxCondition': 'Select tax status', 'agency.billingEmail': 'Billing email', 'agency.contactPhone': 'Contact phone', 'agency.createdAt': 'Creation date', 'agency.nonEditable': 'not editable', 'agency.saveChanges': 'Save changes', 'agency.loading': 'Loading agency information…', 'agency.organization': 'Organization', 'agency.asideTitle': 'An organized foundation to operate', 'agency.asideText': 'This information is used as an institutional reference in TeamBalance administrative processes.',
      'projects.edit': 'Edit project', 'projects.close': 'Close', 'projects.client': 'Client', 'projects.selectClient': 'Select a client', 'projects.newClient': 'New client', 'projects.editClient': 'Edit client', 'projects.pm': 'Project manager', 'projects.selectManager': 'Select a manager', 'projects.status': 'Status', 'projects.planned': 'Planned', 'projects.inProgress': 'In progress', 'projects.completed': 'Completed', 'projects.description': 'Description', 'projects.save': 'Save project', 'projects.clients': 'Agency clients', 'projects.clientsText': 'Manage clients without leaving Projects.', 'projects.agencyProjects': 'Agency projects', 'projects.emptyTitle': 'There are no projects yet', 'projects.emptyText': 'Create a client from the form and start your first project.', 'projects.deactivate': 'Deactivate', 'projects.activate': 'Activate',
      'tasks.editing': 'Editing', 'tasks.newTask': 'New task', 'tasks.close': 'Close', 'tasks.titleLabel': 'Title', 'tasks.project': 'Project', 'tasks.selectProject': 'Select a project', 'tasks.status': 'Status', 'tasks.selectStatus': 'Select a status', 'tasks.assignedTo': 'Assigned to', 'tasks.unassigned': 'Unassigned', 'tasks.priority': 'Priority', 'tasks.complexity': 'Complexity', 'tasks.progress': 'Progress', 'tasks.attachments': 'Attached image URLs (maximum 5)', 'tasks.attachmentsPlaceholder': 'Paste one external URL per line. For example, an image uploaded to Cloudinary.', 'tasks.attachmentsHelp': 'Images are stored as JSON-serialized URLs; TeamBalance does not store files in SQL.', 'tasks.cancel': 'Cancel', 'tasks.catalogEyebrow': 'Catalog', 'tasks.createSkill': 'Create', 'tasks.skillCategory': 'Category', 'tasks.hours': 'estimated h', 'tasks.noPriority': 'No priority', 'tasks.progressAria': 'Progress',
      'employees.supportNote': 'The Support role is only shown to create the first internal TeamBalance user.', 'employees.workEmail': 'Work email', 'employees.temporaryPassword': 'Temporary password', 'employees.temporaryPasswordEdit': 'Temporary password (does not change the current one)', 'employees.roles': 'Roles', 'employees.workProfile': 'Work profile', 'employees.hourCost': 'Hourly cost', 'employees.weeklyHours': 'Available weekly hours', 'employees.seniority': 'Seniority', 'employees.workStatus': 'Employment status', 'employees.startTime': 'Start time', 'employees.endTime': 'End time', 'employees.availabilityNote': 'Availability note', 'employees.skills': 'Employee skills', 'employees.register': 'Register user', 'employees.catalog': 'Skill catalog', 'employees.catalogText': 'Create skills that you can then assign to employees and tasks.', 'employees.createSkill': 'Create skill', 'employees.agencyUsers': 'Agency users', 'employees.user': 'User', 'employees.loadingUsers': 'Loading users…',
      'employees.simpleSearch': 'Simple search', 'employees.simpleSearchPlaceholder': 'Search by name or email', 'employees.advancedSearch': 'Advanced search', 'employees.hideAdvancedSearch': 'Hide advanced filters', 'employees.searchHelp': 'Find users quickly or combine several criteria.', 'employees.all': 'All', 'employees.noResults': 'No users match these filters.',
      'hours.eyebrow': 'My operation', 'hours.title': 'Log hours', 'hours.subtitle': 'Report time dedicated to a task to keep the operational workload updated.', 'hours.task': 'Task', 'hours.taskPlaceholder': 'Select or enter a task', 'hours.date': 'Date', 'hours.hours': 'Hours', 'hours.optionalDescription': 'Optional description', 'hours.descriptionPlaceholder': 'E.g.: deliverable review', 'hours.save': 'Save record', 'hours.success': 'The record is ready to be integrated with task management.',
      'availability.eyebrow': 'My operation', 'availability.title': 'My availability', 'availability.subtitle': 'Keep your capacity visible to improve team planning.', 'availability.schedule': 'Schedule and absences', 'availability.help': 'Set your weekly availability when configuration is enabled.', 'availability.licenses': 'Leaves and absences', 'availability.update': 'Update availability', 'availability.emptyTitle': 'There is no availability registered yet', 'availability.emptyText': 'The schedules, absences and leaves you register will appear here and will be used to plan tasks.',
    }
  };

  readonly language = signal<LanguageCode>((localStorage.getItem('language') as LanguageCode) || 'es');

  readonly culture = signal<CultureCode>((localStorage.getItem('culture') as CultureCode) || 'es-AR');

  cambiarIdioma(language: LanguageCode): void {
    this.language.set(language);
    const culture: CultureCode = language === 'es' ? 'es-AR' : 'en-US';
    this.culture.set(culture);
    localStorage.setItem('language', language);
    localStorage.setItem('culture', culture);
  }

  traducir(key: string, language: LanguageCode = this.language(), fallback?: string): string {
    return this.translations[language][key] ?? fallback ?? key;
  }

  formatearFecha(fecha: Date | string): string {
    return new Intl.DateTimeFormat( this.culture(), { year: 'numeric', month: '2-digit', day: '2-digit',}).format(new Date(fecha));
  }

  formatearFechaHora(fecha: Date | string): string {
    return new Intl.DateTimeFormat(this.culture(), { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit',}).format(new Date(fecha));
  }

  formatearNumero(numero: number): string {

    return new Intl.NumberFormat(
      this.culture()
    ).format(numero);
  }

  formatearMoneda( monto: number, moneda: string = 'USD'): string {
    return new Intl.NumberFormat( this.culture(), { style: 'currency', currency: moneda,}).format(monto);
  }

}
