using System.Data;
using Microsoft.Data.SqlClient;
using TeamBalance.BE.Entidades;
using TeamBalance.DAL;

namespace TeamBalance.MPP;

public class MPPTarea
{
    private readonly Conexion _conexion;
    public MPPTarea(Conexion conexion) { _conexion = conexion; }
    public List<Tarea> Consultar(int idAgencia) { List<SqlParameter> parametros = new List<SqlParameter>() { new SqlParameter("@IdAgencia", idAgencia) }; return CrearTareas(_conexion.Leer("dbo.usp_Tarea_Consultar", parametros)); }
    public Tarea Guardar(Tarea tarea, int idAgencia) { List<SqlParameter> parametros = CrearParametros(tarea, idAgencia); DataTable tabla = _conexion.Leer(tarea.ID == 0 ? "dbo.usp_Tarea_Registrar" : "dbo.usp_Tarea_Modificar", parametros); return CrearTareas(tabla).Single(); }
    public bool CambiarEstado(int idTarea, int idAgencia, bool activo) { List<SqlParameter> parametros = new List<SqlParameter>() { new SqlParameter("@ID", idTarea), new SqlParameter("@IdAgencia", idAgencia), new SqlParameter("@Activo", activo) }; return _conexion.Escribir("dbo.usp_Tarea_CambiarEstado", parametros); }
    public GestionTareaOpciones ConsultarOpciones(int idAgencia)
    {
        List<SqlParameter> parametrosProyectos = new List<SqlParameter>() { new SqlParameter("@IdAgencia", idAgencia) };
        List<SqlParameter> parametrosEstados = new List<SqlParameter>() { new SqlParameter("@IdAgencia", idAgencia) };
        List<SqlParameter> parametrosEmpleados = new List<SqlParameter>() { new SqlParameter("@IdAgencia", idAgencia) };
        List<Proyecto> proyectos = CrearProyectos(_conexion.Leer("dbo.usp_Proyecto_Consultar", parametrosProyectos)); List<EstadoTarea> estados = CrearEstados(_conexion.Leer("dbo.usp_EstadoTarea_Consultar", parametrosEstados)); List<Usuario> empleados = CrearUsuarios(_conexion.Leer("dbo.usp_Tarea_ConsultarEmpleados", parametrosEmpleados)); List<Skill> skills = CrearSkills(_conexion.Leer("dbo.usp_Skill_Consultar"));
        GestionTareaOpciones opciones = new GestionTareaOpciones(proyectos, estados, empleados, skills); return opciones;
    }
    private static List<SqlParameter> CrearParametros(Tarea tarea, int idAgencia) { List<SqlParameter> parametros = new List<SqlParameter>() { new SqlParameter("@ID", tarea.ID), new SqlParameter("@IdAgencia", idAgencia), new SqlParameter("@IdProyecto", tarea.IdProyecto), new SqlParameter("@IdEmpleadoAsignado", (object?)tarea.IdEmpleadoAsignado ?? DBNull.Value), new SqlParameter("@IdSkillRequerido", (object?)tarea.IdSkillRequerido ?? DBNull.Value), new SqlParameter("@IdEstadoTarea", tarea.IdEstadoTarea), new SqlParameter("@Titulo", tarea.Titulo), new SqlParameter("@Descripcion", (object?)tarea.Descripcion ?? DBNull.Value), new SqlParameter("@Prioridad", (object?)tarea.Prioridad ?? DBNull.Value), new SqlParameter("@Complejidad", (object?)tarea.Complejidad ?? DBNull.Value), new SqlParameter("@FechaInicio", (object?)tarea.FechaInicio ?? DBNull.Value), new SqlParameter("@Deadline", (object?)tarea.Deadline ?? DBNull.Value), new SqlParameter("@SeniorityRequerido", (object?)tarea.SeniorityRequerido ?? DBNull.Value), new SqlParameter("@PorcentajeAvance", tarea.PorcentajeAvance), new SqlParameter("@HorasEstimadas", tarea.HorasEstimadas) }; return parametros; }
    private static List<Tarea> CrearTareas(DataTable tabla) { List<Tarea> tareas = new List<Tarea>(); foreach (DataRow fila in tabla.Rows) { Tarea tarea = new Tarea(Convert.ToInt32(fila["ID"]), Convert.ToInt32(fila["IdProyecto"]), fila["IdEmpleadoAsignado"] == DBNull.Value ? null : Convert.ToInt32(fila["IdEmpleadoAsignado"]), fila["IdSkillRequerido"] == DBNull.Value ? null : Convert.ToInt32(fila["IdSkillRequerido"]), Convert.ToInt32(fila["IdEstadoTarea"]), null, Convert.ToString(fila["Titulo"]) ?? string.Empty, Convert.ToString(fila["Descripcion"]), Convert.ToString(fila["Estado"]), Convert.ToString(fila["Prioridad"]), Convert.ToString(fila["Complejidad"]), fila["FechaInicio"] == DBNull.Value ? null : Convert.ToDateTime(fila["FechaInicio"]), fila["Deadline"] == DBNull.Value ? null : Convert.ToDateTime(fila["Deadline"]), null, Convert.ToString(fila["SeniorityRequerido"]), null, null, null, false, null, Convert.ToDecimal(fila["PorcentajeAvance"]), Convert.ToDecimal(fila["HorasEstimadas"]), Convert.ToBoolean(fila["Activo"]), fila["FechaBaja"] == DBNull.Value ? null : Convert.ToDateTime(fila["FechaBaja"])); tareas.Add(tarea); } return tareas; }
    private static List<Proyecto> CrearProyectos(DataTable tabla) { List<Proyecto> proyectos = new List<Proyecto>(); foreach (DataRow fila in tabla.Rows) { Proyecto proyecto = new Proyecto(Convert.ToInt32(fila["ID"]), Convert.ToInt32(fila["IdAgencia"]), Convert.ToInt32(fila["IdCliente"]), Convert.ToInt32(fila["IdPMResponsable"]), Convert.ToString(fila["Nombre"]) ?? string.Empty, Convert.ToString(fila["Descripcion"]), null, null, Convert.ToDecimal(fila["HorasEstimadasTotales"]), Convert.ToString(fila["Estado"]) ?? string.Empty, Convert.ToBoolean(fila["Activo"]), Convert.ToDateTime(fila["FechaAlta"]), null); proyectos.Add(proyecto); } return proyectos; }
    private static List<EstadoTarea> CrearEstados(DataTable tabla) { List<EstadoTarea> estados = new List<EstadoTarea>(); foreach (DataRow fila in tabla.Rows) { EstadoTarea estado = new EstadoTarea(Convert.ToInt32(fila["ID"]), Convert.ToInt32(fila["IdAgencia"]), Convert.ToString(fila["Nombre"]) ?? string.Empty, Convert.ToInt32(fila["Orden"]), Convert.ToBoolean(fila["EsBase"]), Convert.ToBoolean(fila["EsFinal"]), Convert.ToBoolean(fila["Activo"])); estados.Add(estado); } return estados; }
    private static List<Usuario> CrearUsuarios(DataTable tabla) { List<Usuario> usuarios = new List<Usuario>(); foreach (DataRow fila in tabla.Rows) { Usuario usuario = new Usuario(Convert.ToInt32(fila["ID"]), Convert.ToInt32(fila["IdAgencia"]), new Rol(), Convert.ToString(fila["Nombre"]) ?? string.Empty, Convert.ToString(fila["Apellido"]) ?? string.Empty, Convert.ToString(fila["Email"]) ?? string.Empty, string.Empty, string.Empty, DateTime.MinValue, true); usuarios.Add(usuario); } return usuarios; }
    private static List<Skill> CrearSkills(DataTable tabla) { List<Skill> skills = new List<Skill>(); foreach (DataRow fila in tabla.Rows) { Skill skill = new Skill(Convert.ToInt32(fila["ID"]), Convert.ToString(fila["Nombre"]) ?? string.Empty, Convert.ToString(fila["Categoria"]), Convert.ToBoolean(fila["Activo"])); skills.Add(skill); } return skills; }
}
