<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeamBalance.BE\TeamBalance.BE.csproj" />
    <ProjectReference Include="..\TeamBalance.DAL\TeamBalance.DAL.csproj" />
  </ItemGroup>

</Project>
